/* JS */ gapi.loaded_1(function(_){var window=this;
_.Tc=_.Ka(_.bb,"rw",_.r());
var Uc=function(a,c){(a=_.Tc[a])&&a.state<c&&(a.state=c)};var Vc=function(a){a=(a=_.Tc[a])?a.oid:void 0;if(a){var c=_.ua.getElementById(a);c&&c.parentNode.removeChild(c);delete _.Tc[a];Vc(a)}};_.bf=function(a){a=a.container;"string"===typeof a&&(a=window.document.getElementById(a));return a};_.gf=function(a){var c=a.clientWidth;return"position:absolute;top:-10000px;width:"+(c?c+"px":a.style.width||"300px")+";margin:0px;border-style:none;"};
_.hf=function(a,c){var f={},g=a.va(),h=c&&c.width,l=c&&c.height,n=c&&c.verticalAlign;n&&(f.verticalAlign=n);h||(h=g.width||a.width);l||(l=g.height||a.height);g.width=f.width=h;g.height=f.height=l;g=a.rb();h=a.Hh();Uc(h,2);a:{h=a.V();f=f||{};if(_.bb.oa){var q=g.id;if(q){l=(l=_.Tc[q])?l.state:void 0;if(1===l||4===l)break a;Vc(q)}}(l=h.nextSibling)&&l.getAttribute&&l.getAttribute("data-gapistub")&&(h.parentNode.removeChild(l),h.style.cssText="");l=f.width;n=f.height;var t=h.style;t.textIndent="0";t.margin=
"0";t.padding="0";t.background="transparent";t.borderStyle="none";t.cssFloat="none";t.styleFloat="none";t.lineHeight="normal";t.fontSize="1px";t.verticalAlign="baseline";h=h.style;h.display="inline-block";g=g.style;g.position="static";g.left="0";g.top="0";g.visibility="visible";l&&(h.width=g.width=l+"px");n&&(h.height=g.height=n+"px");f.verticalAlign&&(h.verticalAlign=f.verticalAlign);q&&Uc(q,3)}(q=c?c.title:null)&&a.rb().setAttribute("title",q);(c=c?c.ariaLabel:null)&&a.rb().setAttribute("aria-label",
c)};_.jf=function(a){var c=a.V();c&&c.removeChild(a.rb())};_.Ru=function(a){a.where=_.bf(a);var c=a.messageHandlers=a.messageHandlers||{},f=function(a){_.hf(this,a)};c._ready=f;c._renderstart=f;var g=a.onClose;a.onClose=function(a){g&&g.call(this,a);_.jf(this)};a.onCreate=function(a){a=a.rb();a.style.cssText=_.gf(a)}};

var cr=_.Rb=_.Rb||{};window.___jsl=window.___jsl||{};cr.aX={dja:function(){return window.___jsl.bsh},Ok:function(){return window.___jsl.h},NT:function(a){window.___jsl.bsh=a},ys:function(a){window.___jsl.h=a}};
_.R=_.R||{};_.R.Dg=function(a,c,f){for(var g=[],h=2,l=arguments.length;h<l;++h)g.push(arguments[h]);return function(){for(var f=g.slice(),h=0,l=arguments.length;h<l;++h)f.push(arguments[h]);return c.apply(a,f)}};_.R.nf=function(a){var c,f,g={};for(c=0;f=a[c];++c)g[f]=f;return g};

_.R=_.R||{};
(function(){function a(a,c){return String.fromCharCode(c)}var c={0:!1,10:!0,13:!0,34:!0,39:!0,60:!0,62:!0,92:!0,8232:!0,8233:!0,65282:!0,65287:!0,65308:!0,65310:!0,65340:!0};_.R.escape=function(a,c){if(a){if("string"===typeof a)return _.R.Qf(a);if("Array"===typeof a){var f=0;for(c=a.length;f<c;++f)a[f]=_.R.escape(a[f])}else if("object"===typeof a&&c){c={};for(f in a)a.hasOwnProperty(f)&&(c[_.R.Qf(f)]=_.R.escape(a[f],!0));return c}}return a};_.R.Qf=function(a){if(!a)return a;for(var f=[],h,l,n=0,q= a.length;n<q;++n)h=a.charCodeAt(n),l=c[h],!0===l?f.push("&#",h,";"):!1!==l&&f.push(a.charAt(n));return f.join("")};_.R.YX=function(c){return c?c.replace(/&#([0-9]+);/g,a):c}})();

(function(){function a(a,c){if(!(a<f)&&g)if(2===a&&g.warn)g.warn(c);else if(3===a&&g.error)try{g.error(c)}catch(n){}else g.log&&g.log(c)}var c=function(c){a(1,c)};_.Lb=function(c){a(2,c)};_.sa=function(c){a(3,c)};_.Fc=function(){};c.INFO=1;c.WARNING=2;c.NONE=4;var f=1,g=window.console?window.console:window.opera?window.opera.postError:void 0;return c})();

_.R=_.R||{};(function(){var a=[];_.R.du=function(c){a.push(c)};_.R.XX=function(){for(var c=0,f=a.length;c<f;++c)a[c]()}})();
_.Pb=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&_.Fa(a());return{register:function(a,f,g){g&&g(_.P())},get:function(a){return _.P(a)},update:function(a,f){if(f)throw"Config replacement is not supported";_.Fa(a)},kc:function(){}}}();
_.Mu("gadgets.config.register",_.Pb.register);_.Mu("gadgets.config.get",_.Pb.get);_.Mu("gadgets.config.init",_.Pb.kc);_.Mu("gadgets.config.update",_.Pb.update);
var Qb;_.Ma=function(){var a=_.ua.readyState;return"complete"===a||"interactive"===a&&-1==window.navigator.userAgent.indexOf("MSIE")};_.Wa=function(a){if(_.Ma())a();else{var c=!1,f=function(){if(!c)return c=!0,a.apply(this,arguments)};_.ta.addEventListener?(_.ta.addEventListener("load",f,!1),_.ta.addEventListener("DOMContentLoaded",f,!1)):_.ta.attachEvent&&(_.ta.attachEvent("onreadystatechange",function(){_.Ma()&&f.apply(this,arguments)}),_.ta.attachEvent("onload",f))}};Qb=Qb||{};Qb.Km=null; Qb.bm=null;Qb.FM=null;Qb.frameElement=null;
Qb=Qb||{};
Qb.Lj||(Qb.Lj=function(){function a(a,c,f){"undefined"!=typeof window.addEventListener?window.addEventListener(a,c,f):"undefined"!=typeof window.attachEvent&&window.attachEvent("on"+a,c);"message"===a&&(window.___jsl=window.___jsl||{},a=window.___jsl,a.RPMQ=a.RPMQ||[],a.RPMQ.push(c))}function c(a){var c=_.of(a.data);if(c&&c.f){(0,_.Fc)("gadgets.rpc.receive("+window.name+"): "+a.data);var g=_.T.$d(c.f);h&&("undefined"!==typeof a.origin?a.origin!==g:a.domain!==/^.+:\/\/([^:]+).*/.exec(g)[1])?_.sa("Invalid rpc message origin. "+
g+" vs "+(a.origin||"")):f(c,a.origin)}}var f,g,h=!0;return{Kk:function(){return"wpm"},jga:function(){return!0},kc:function(l,n){_.Pb.register("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(h=!1)});f=l;g=n;a("message",c,!1);g("..",!0);return!0},sf:function(a){g(a,!0);return!0},call:function(a,c,f){var g=_.T.$d(a),h=_.T.dk(a);g?window.setTimeout(function(){var a=_.mf(f);(0,_.Fc)("gadgets.rpc.send("+window.name+"): "+a);h.postMessage(a,g)},0):".."!=a&&_.sa("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.T&&_.T||(_.T=window.gadgets.rpc,_.T.config=_.T.config,_.T.register=_.T.register,_.T.unregister=_.T.unregister,_.T.Am=_.T.registerDefault,_.T.aB=_.T.unregisterDefault,_.T.Fk=_.T.forceParentVerifiable,_.T.call=_.T.call,_.T.Rk=_.T.getRelayUrl,_.T.Xg=_.T.setRelayUrl,_.T.Wg=_.T.setAuthToken,_.T.tf=_.T.setupReceiver,_.T.Wd=_.T.getAuthToken,_.T.mj=_.T.removeReceiver,_.T.Qk=_.T.getRelayChannel,_.T.ym=_.T.receive,_.T.zm=_.T.receiveSameDomain,_.T.Pq=
_.T.getOrigin,_.T.$d=_.T.getTargetOrigin,_.T.dk=_.T._getTargetWin,_.T.Uo=_.T._parseSiblingId);else{_.T=function(){function a(a,c){if(!Ta[a]){var f=fc;c||(f=te);Ta[a]=f;c=Ya[a]||[];for(var g=0;g<c.length;++g){var h=c[g];h.t=ka[a];f.call(a,h.f,h)}Ya[a]=[]}}function c(){function a(){Go=!0}Ho||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),Ho=!0)}function f(a,f,g,h,l){ka[f]&&ka[f]===g||(_.sa("Invalid gadgets.rpc token. "+
ka[f]+" vs "+g),ok(f,2));l.onunload=function(){ja[f]&&!Go&&(ok(f,1),_.T.mj(f))};c();h=_.of((0,window.decodeURIComponent)(h))}function g(c,f){if(c&&"string"===typeof c.s&&"string"===typeof c.f&&c.a instanceof Array)if(ka[c.f]&&ka[c.f]!==c.t&&(_.sa("Invalid gadgets.rpc token. "+ka[c.f]+" vs "+c.t),ok(c.f,2)),"__ack"===c.s)window.setTimeout(function(){a(c.f,!0)},0);else{c.c&&(c.callback=function(a){_.T.call(c.f,(c.g?"legacy__":"")+"__cb",null,c.c,a)});if(f){var g=h(f);c.origin=f;var l=c.r;try{var n=
h(l)}catch($B){}l&&n==g||(l=f);c.referer=l}f=(E[c.s]||E[""]).apply(c,c.a);c.c&&"undefined"!==typeof f&&_.T.call(c.f,"__cb",null,c.c,f)}}function h(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==
a&&"android-app"!==a&&"chrome-search"!==a)throw Error("Pa");f="";var g=c.indexOf(":");if(-1!=g){var h=c.substring(g+1);c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f}function l(a){if("/"==a.charAt(0)){var c=a.indexOf("|");return{id:0<c?a.substring(1,c):a.substring(1),origin:0<c?a.substring(c+1):null}}return null}function n(a){if("undefined"===typeof a||".."===a)return window.parent;var c=l(a);if(c)return window.top.frames[c.id];a=String(a);return(c=window.frames[a])?
c:(c=window.document.getElementById(a))&&c.contentWindow?c.contentWindow:null}function q(a,c){if(!0!==ja[a]){"undefined"===typeof ja[a]&&(ja[a]=0);var f=n(a);".."!==a&&null==f||!0!==fc.sf(a,c)?!0!==ja[a]&&10>ja[a]++?window.setTimeout(function(){q(a,c)},500):(Ta[a]=te,ja[a]=!0):ja[a]=!0}}function t(a){(a=K[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function v(a,c,f){c&&!/http(s)?:\/\/.+/.test(c)&&
(0==c.indexOf("//")?c=window.location.protocol+c:"/"==c.charAt(0)?c=window.location.protocol+"//"+window.location.host+c:-1==c.indexOf("://")&&(c=window.location.protocol+"//"+c));K[a]=c;"undefined"!==typeof f&&(U[a]=!!f)}function w(a,c){c=c||"";ka[a]=String(c);q(a,c)}function A(a){a=(a.passReferrer||"").split(":",2);If=a[0]||"none";wh=a[1]||"origin"}function F(c){"true"===String(c.useLegacyProtocol)&&(fc=Qb.FM||te,fc.kc(g,a))}function z(a,c){function f(f){f=f&&f.rpc||{};A(f);var g=f.parentRelayUrl||
"";g=h(rw.parent||c)+g;v("..",g,"true"===String(f.useLegacyProtocol));F(f);w("..",a)}!rw.parent&&c?f({}):_.Pb.register("rpc",null,f)}function I(a,c,f){if(".."===a)z(f||rw.rpctoken||rw.ifpctok||"",c);else a:{var g=null;if("/"!=a.charAt(0)){if(!_.R)break a;g=window.document.getElementById(a);if(!g)throw Error("h`"+a);}g=g&&g.src;c=c||_.T.Pq(g);v(a,c);c=_.R.Qc(g);w(a,f||c.rpctoken)}}var E={},K={},U={},ka={},S=0,Ca={},ja={},rw={},Ta={},Ya={},If=null,wh=null,nk=window.top!==window.self,Yw=window.name,
ok=function(){},pk=window.console,Io=pk&&pk.log&&function(a){pk.log(a)}||function(){},te=function(){function a(a){return function(){Io(a+": call ignored")}}return{Kk:function(){return"noop"},jga:function(){return!0},kc:a("init"),sf:a("setup"),call:a("call")}}();_.R&&(rw=_.R.Qc());var Go=!1,Ho=!1,fc=function(){if("rmr"==rw.rpctx)return Qb.Km;var a="function"===typeof window.postMessage?Qb.Lj:"object"===typeof window.postMessage?Qb.Lj:window.ActiveXObject?Qb.bm?Qb.bm:Qb.FM:0<window.navigator.userAgent.indexOf("WebKit")?
Qb.Km:"Gecko"===window.navigator.product?Qb.frameElement:Qb.FM;a||(a=te);return a}();E[""]=function(){Io("Unknown RPC service: "+this.s)};E.__cb=function(a,c){var f=Ca[a];f&&(delete Ca[a],f.call(this,c))};return{config:function(a){"function"===typeof a.Mm&&(ok=a.Mm)},register:function(a,c){if("__cb"===a||"__ack"===a)throw Error("i");if(""===a)throw Error("j");E[a]=c},unregister:function(a){if("__cb"===a||"__ack"===a)throw Error("k");if(""===a)throw Error("l");delete E[a]},Am:function(a){E[""]=a},
aB:function(){delete E[""]},Fk:function(){},call:function(a,c,f,g){a=a||"..";var h="..";".."===a?h=Yw:"/"==a.charAt(0)&&(h=_.T.Pq(window.location.href),h="/"+Yw+(h?"|"+h:""));++S;f&&(Ca[S]=f);var n={s:c,f:h,c:f?S:0,a:Array.prototype.slice.call(arguments,3),t:ka[a],l:!!U[a]};a:if("bidir"===If||"c2p"===If&&".."===a||"p2c"===If&&".."!==a){var q=window.location.href;var t="?";if("query"===wh)t="#";else if("hash"===wh)break a;t=q.lastIndexOf(t);t=-1===t?q.length:t;q=q.substring(0,t)}else q=null;q&&(n.r=
q);if(".."===a||null!=l(a)||window.document.getElementById(a))(q=Ta[a])||null===l(a)||(q=fc),0===c.indexOf("legacy__")&&(q=fc,n.s=c.substring(8),n.c=n.c?n.c:S),n.g=!0,n.r=h,q?(U[a]&&(q=Qb.FM),!1===q.call(a,h,n)&&(Ta[a]=te,fc.call(a,h,n))):Ya[a]?Ya[a].push(n):Ya[a]=[n]},Rk:t,Xg:v,Wg:w,tf:I,Wd:function(a){return ka[a]},mj:function(a){delete K[a];delete U[a];delete ka[a];delete ja[a];delete Ta[a]},Qk:function(){return fc.Kk()},ym:function(a,c){4<a.length?fc.Vo(a,g):f.apply(null,a.concat(c))},zm:function(a){a.a=
Array.prototype.slice.call(a.a);window.setTimeout(function(){g(a)},0)},Pq:h,$d:function(a){var c=null,f=t(a);f?c=f:(f=l(a))?c=f.origin:".."==a?c=rw.parent:(a=window.document.getElementById(a))&&"iframe"===a.tagName.toLowerCase()&&(c=a.src);return h(c)},kc:function(){!1===fc.kc(g,a)&&(fc=te);nk?I(".."):_.Pb.register("rpc",null,function(a){a=a.rpc||{};A(a);F(a)})},dk:n,Uo:l,Iia:"__ack",lh:Yw||"..",Pia:0,Oia:1,Nia:2}}();_.T.kc()};
_.T.config({Mm:function(a){throw Error("m`"+a);}});_.Fc=_.ke;_.Mu("gadgets.rpc.config",_.T.config);_.Mu("gadgets.rpc.register",_.T.register);_.Mu("gadgets.rpc.unregister",_.T.unregister);_.Mu("gadgets.rpc.registerDefault",_.T.Am);_.Mu("gadgets.rpc.unregisterDefault",_.T.aB);_.Mu("gadgets.rpc.forceParentVerifiable",_.T.Fk);_.Mu("gadgets.rpc.call",_.T.call);_.Mu("gadgets.rpc.getRelayUrl",_.T.Rk);_.Mu("gadgets.rpc.setRelayUrl",_.T.Xg);_.Mu("gadgets.rpc.setAuthToken",_.T.Wg);_.Mu("gadgets.rpc.setupReceiver",_.T.tf);_.Mu("gadgets.rpc.getAuthToken",_.T.Wd); _.Mu("gadgets.rpc.removeReceiver",_.T.mj);_.Mu("gadgets.rpc.getRelayChannel",_.T.Qk);_.Mu("gadgets.rpc.receive",_.T.ym);_.Mu("gadgets.rpc.receiveSameDomain",_.T.zm);_.Mu("gadgets.rpc.getOrigin",_.T.Pq);_.Mu("gadgets.rpc.getTargetOrigin",_.T.$d);

_.R=_.R||{};_.R.Ee=function(a,c,f,g){"undefined"!=typeof a.addEventListener?a.addEventListener(c,f,g):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,f):_.Lb("cannot attachBrowserEvent: "+c)};_.R.Vr=function(a){var c=window;c.removeEventListener?c.removeEventListener("mousemove",a,!1):c.detachEvent?c.detachEvent("onmousemove",a):_.Lb("cannot removeBrowserEvent: mousemove")};

_.Tb=function(){function a(){h[0]=1732584193;h[1]=4023233417;h[2]=2562383102;h[3]=271733878;h[4]=3285377520;w=v=0}function c(a){for(var c=n,f=0;64>f;f+=4)c[f/4]=a[f]<<24|a[f+1]<<16|a[f+2]<<8|a[f+3];for(f=16;80>f;f++)a=c[f-3]^c[f-8]^c[f-14]^c[f-16],c[f]=(a<<1|a>>>31)&4294967295;a=h[0];var g=h[1],l=h[2],q=h[3],t=h[4];for(f=0;80>f;f++){if(40>f)if(20>f){var v=q^g&(l^q);var w=1518500249}else v=g^l^q,w=1859775393;else 60>f?(v=g&l|q&(g|l),w=2400959708):(v=g^l^q,w=3395469782);v=((a<<5|a>>>27)&4294967295)+
v+t+w+c[f]&4294967295;t=q;q=l;l=(g<<30|g>>>2)&4294967295;g=a;a=v}h[0]=h[0]+a&4294967295;h[1]=h[1]+g&4294967295;h[2]=h[2]+l&4294967295;h[3]=h[3]+q&4294967295;h[4]=h[4]+t&4294967295}function f(a,f){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var g=[],h=0,n=a.length;h<n;++h)g.push(a.charCodeAt(h));a=g}f||(f=a.length);g=0;if(0==v)for(;g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64;for(;g<f;)if(l[v++]=a[g++],w++,64==v)for(v=0,c(l);g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64}
function g(){var a=[],g=8*w;56>v?f(q,56-v):f(q,64-(v-56));for(var n=63;56<=n;n--)l[n]=g&255,g>>>=8;c(l);for(n=g=0;5>n;n++)for(var t=24;0<=t;t-=8)a[g++]=h[n]>>t&255;return a}for(var h=[],l=[],n=[],q=[128],t=1;64>t;++t)q[t]=0;var v,w;a();return{reset:a,update:f,digest:g,Of:function(){for(var a=g(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c}}};
_.Vb=function(){function a(a){var c=_.Tb();c.update(a);return c.Of()}var c=window.crypto;if(c&&"function"==typeof c.getRandomValues)return function(){var a=new window.Uint32Array(1);c.getRandomValues(a);return Number("0."+a[0])};var f=_.P("random/maxObserveMousemove");null==f&&(f=-1);var g=0,h=Math.random(),l=1,n=1E6*(window.screen.width*window.screen.width+window.screen.height),q=function(a){a=a||window.event;var c=a.screenX+a.clientX<<16;c+=a.screenY+a.clientY;c*=(new Date).getTime()%1E6;l=l*c%
n;0<f&&++g==f&&_.R.Vr(q)};0!=f&&_.R.Ee(window,"mousemove",q,!1);var t=a(window.document.cookie+"|"+window.document.location+"|"+(new Date).getTime()+"|"+h);return function(){var c=l;c+=(0,window.parseInt)(t.substr(0,20),16);t=a(t);return c/(n+Math.pow(16,20))}}();
_.Mu("shindig.random",_.Vb);
_.V={};_.Sb={};window.iframer=_.Sb;
_.V.Kh=_.V.Kh||{};_.V.Kh.jp=function(a){try{return!!a.document}catch(c){}return!1};_.V.Kh.Uk=function(a){var c=a.parent;return a!=c&&_.V.Kh.jp(c)?_.V.Kh.Uk(c):a};_.V.Kh.St=function(a){var c=a.userAgent||"";a=a.product||"";return 0!=c.indexOf("Opera")&&-1==c.indexOf("WebKit")&&"Gecko"==a&&0<c.indexOf("rv:1.")};

var gc,ic,bG,oc,qc,hG,uc,vc,eo,xc,yc,Mc,Nc,Oc,Qc,ec;gc=function(){_.V.Kl++;return["I",_.V.Kl,"_",(new Date).getTime()].join("")};ic=function(a){return a instanceof Array?a.join(","):a instanceof Object?_.mf(a):a};bG=function(a){var c=_.P("googleapis.config/elog");if(c)try{c(a)}catch(f){}};oc=function(a){a&&a.match(pc)&&_.Fa("googleapis.config/gcv",a)};qc=function(a){_.Rb.aX.ys(a)};hG=function(a){_.Rb.aX.NT(a)};_.sc=function(a,c){c=c||{};for(var f in a)a.hasOwnProperty(f)&&(c[f]=a[f]);return c};
_.tc=function(a,c,f,g,h){var l=[],n;for(n in a)if(a.hasOwnProperty(n)){var q=c,t=f,v=a[n],w=g,A=Zb(n);A[q]=A[q]||{};w=_.R.Dg(w,v);v._iframe_wrapped_rpc_&&(w._iframe_wrapped_rpc_=!0);A[q][t]=w;l.push(n)}if(h)for(n in _.V.uW)_.V.uW.hasOwnProperty(n)&&l.push(n);return l.join(",")};uc=function(a,c,f){var g={};if(a&&a._methods){a=a._methods.split(",");for(var h=0;h<a.length;h++){var l=a[h];g[l]=$b(l,c,f)}}return g};
vc=function(a){if(a&&a.disableMultiLevelParentRelay)a=!1;else{var c;if(c=_.Sb&&_.Sb._open&&"inline"!=a.style&&!0!==a.inline)a=a.container,c=!(a&&("string"==typeof a&&window.document.getElementById(a)||window.document==(a.ownerDocument||a.document)));a=c}return a};eo=function(a,c){var f={};c=c.params||{};for(var g in a)"#"==g.charAt(0)&&(f[g.substring(1)]=a[g]),0==g.indexOf("fr-")&&(f[g.substring(3)]=a[g]),"#"==c[g]&&(f[g]=a[g]);for(var h in f)delete a["fr-"+h],delete a["#"+h],delete a[h];return f};
xc=function(a){if(":"==a.charAt(0)){var c=_.P("iframes/"+a.substring(1));a={};_.Sl(c,a);(c=a.url)&&(a.url=_.mc(c));a.params||(a.params={});return a}return{url:_.mc(a)}};yc=function(a){function c(){}c.prototype=zc.prototype;a.prototype=new c};Mc=function(a){return _.V.yf[a]};Nc=function(a,c){_.V.yf[a]=c};Oc=function(a){a=a||{};"auto"===a.height&&(a.height=_.Ob.Cd());var c=window&&Pc&&Pc.ma();c?c.Gm(a.width||0,a.height||0):_.Sb&&_.Sb._resizeMe&&_.Sb._resizeMe(a)};Qc=function(a){oc(a)};
_.ba=function(){return _.ta.location.origin||_.ta.location.protocol+"//"+_.ta.location.host};ec=function(a){var c=_.e(a.location.href,"urlindex");if(c=_.Ka(_.bb,"fUrl",[])[c]){var f=a.location.hash;c+=/#/.test(c)?f.replace(/^#/,"&"):f;a.location.replace(c)}};
if(window.ToolbarApi)Pc=window.ToolbarApi,Pc.ma=window.ToolbarApi.getInstance,Pc.prototype=window.ToolbarApi.prototype,_.k=Pc.prototype,_.k.openWindow=Pc.prototype.openWindow,_.k.rk=Pc.prototype.closeWindow,_.k.Tm=Pc.prototype.setOnCloseHandler,_.k.jj=Pc.prototype.canClosePopup,_.k.Gm=Pc.prototype.resizeWindow;else{var Pc=function(){},Rc=null;Pc.ma=function(){!Rc&&window.external&&window.external.GTB_IsToolbar&&(Rc=new Pc);return Rc};_.k=Pc.prototype;_.k.openWindow=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.k.rk=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.k.Tm=function(a,c){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,c)};_.k.jj=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.k.Gm=function(a,c){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,c)};window.ToolbarApi=Pc;window.ToolbarApi.getInstance=Pc.ma};
var iH=function(){_.T.register("_noop_echo",function(){this.callback(_.V.UI(_.V.Uc[this.f]))})},ac=function(){window.setTimeout(function(){_.T.call("..","_noop_echo",_.V.Lr)},0)},$b=function(a,c,f){var g=function(g){var h=Array.prototype.slice.call(arguments,0),n=h[h.length-1];if("function"===typeof n){var q=n;h.pop()}h.unshift(c,a,q,f);_.T.call.apply(_.T,h)};g._iframe_wrapped_rpc_=!0;return g},Zb=function(a){_.V.Rg[a]||(_.V.Rg[a]={},_.T.register(a,function(c,f){var g=this.f;if(!("string"!=typeof c||
c in{}||g in{})){var h=this.callback,l=_.V.Rg[a][g],n;l&&Object.hasOwnProperty.call(l,c)?n=l[c]:Object.hasOwnProperty.call(_.V.uW,a)&&(n=_.V.uW[a]);if(n)return g=Array.prototype.slice.call(arguments,1),n._iframe_wrapped_rpc_&&h&&g.push(h),n.apply({},g)}_.sa(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',c,'" from frame "',g,'".'].join(""));return null}));return _.V.Rg[a]};
_.V.ip=function(a,c,f){var g=Array.prototype.slice.call(arguments);_.V.Pk(function(a){a.sameOrigin&&(g.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.T.call.apply(_.T,g))})};_.V.Sr=function(a,c){_.T.register(a,c)};
var pc=/^[-_.0-9A-Za-z]+$/,Hc={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"},Jc={onBeforeParentOpen:"beforeparentopen"},Cc={onOpen:function(a){var c=a.va();a.Pa(c.container||c.element);return a},onClose:function(a){a.remove()}};_.V.Wp=function(a){var c=_.r();_.Sl(_.vb,c);_.Sl(a,c);return c};
var zc=function(a,c,f,g,h,l,n,q){this.config=xc(a);this.openParams=this.DW=c||{};this.params=f||{};this.methods=g;this.qy=!1;Ac(this,c.style);this.Aq={};Bc(this,function(){var a;(a=this.DW.style)&&_.V.yf[a]?a=_.V.yf[a]:a?(_.Lb(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=null):a=Cc;if(a){if("function"===typeof a)var c=a(this);else{var f={};for(c in a){var g=a[c];f[c]="function"===typeof g?_.R.Dg(a,g,this):g}c=f}for(var n in h)a=c[n],"function"===typeof a&&Dc(this,
h[n],_.R.Dg(c,a))}l&&Dc(this,"close",l)});this.ya=this.ac=n;this.dj=(q||[]).slice();n&&this.dj.unshift(n.Hh())};zc.prototype.va=function(){return this.DW};zc.prototype.tb=function(){return this.params};zc.prototype.LW=function(){return this.methods};zc.prototype.ua=function(){return this.ya};var Ac=function(a,c){a.qy||((c=c&&!_.V.yf[c]&&_.V.XR[c])?(a.kz=[],c(function(){a.qy=!0;for(var c=0,g=a.kz.length;c<g;++c)a.kz[c].call(a)})):a.qy=!0)},Bc=function(a,c){a.qy?c.call(a):a.kz.push(c)};
zc.prototype.zh=function(a,c){Bc(this,function(){Dc(this,a,c)})};var Dc=function(a,c,f){a.Aq[c]=a.Aq[c]||[];a.Aq[c].push(f)};zc.prototype.Ub=function(a,c){Bc(this,function(){var f=this.Aq[a];if(f)for(var g=0,h=f.length;g<h;++g)if(f[g]===c){f.splice(g,1);break}})};
zc.prototype.Pb=function(a,c){var f=this.Aq[a];if(f)for(var g=Array.prototype.slice.call(arguments,1),h=0,l=f.length;h<l;++h)try{var n=f[h].apply({},g)}catch(q){_.sa(['Exception when calling callback "',a,'" with exception "',q.name,": ",q.message,'".'].join("")),bG(q)}return n};
var Ec=function(a){return"number"==typeof a?{value:a,od:a+"px"}:"100%"==a?{value:100,od:"100%",Ul:!0}:null},Gc=function(a,c,f,g,h,l,n){zc.call(this,a,c,f,g,Hc,h,l,n);this.id=c.id||gc();this.J2=c.rpctoken&&String(c.rpctoken)||Math.round(1E9*(0,_.Vb)());this.Qfa=eo(this.params,this.config);this.Cz={};Bc(this,function(){this.Pb("open");_.sc(this.Cz,this)})};yc(Gc);_.k=Gc.prototype;
_.k.Pa=function(a,c){if(!this.config.url)return _.sa("Cannot open iframe, empty URL."),this;var f=this.id;_.V.Uc[f]=this;var g=_.sc(this.methods);g._ready=this.Jg;g._close=this.close;g._open=this.T4;g._resizeMe=this.w0;g._renderstart=this.PA;var h=this.Qfa;this.J2&&(h.rpctoken=this.J2);h._methods=_.tc(g,f,"",this,!0);this.el=a="string"===typeof a?window.document.getElementById(a):a;g={};g.id=f;if(c){g.attributes=c;var l=c.style;if("string"===typeof l){if(l){var n=[];l=l.split(";");for(var q=0,t=l.length;q<
t;++q){var v=l[q];if(0!=v.length||q+1!=t)v=v.split(":"),2==v.length&&v[0].match(/^[ a-zA-Z_-]+$/)&&v[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?n.push(v.join(":")):_.sa(['Iframe style "',l[q],'" not allowed.'].join(""))}n=n.join(";")}else n="";c.style=n}}this.va().allowPost&&(g.allowPost=!0);this.va().forcePost&&(g.forcePost=!0);g.queryParams=this.params;g.fragmentParams=h;g.paramsSerializer=ic;this.jJ=_.tb(this.config.url,a,g);a=this.jJ.getAttribute("data-postorigin")||this.jJ.src;_.V.Uc[f]=this;_.T.Wg(this.id,
this.J2);_.T.Xg(this.id,a);return this};_.k.fg=function(a,c){this.Cz[a]=c};_.k.Hh=function(){return this.id};_.k.rb=function(){return this.jJ};_.k.V=function(){return this.el};_.k.qc=function(a){this.el=a};_.k.Jg=function(a){var c=uc(a,this.id,"");this.ya&&"function"==typeof this.methods._ready&&(a._methods=_.tc(c,this.ya.Hh(),this.id,this,!1),this.methods._ready(a));_.sc(a,this);_.sc(c,this);this.Pb("ready",a)};_.k.PA=function(a){this.Pb("renderstart",a)};
_.k.close=function(a){a=this.Pb("close",a);delete _.V.Uc[this.id];return a};_.k.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.k.T4=function(a){var c=uc(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.el);if(vc(a.openParams))new Ic(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain);else{var f=new Gc(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain),g=this;Bc(f,function(){var a={childId:f.Hh()},l=f.Cz;l._toclose=f.close;a._methods=_.tc(l,g.id,f.id,f,!1);c._onopen(a)})}};
_.k.w0=function(a){if(void 0===this.Pb("resize",a)&&this.jJ){var c=Ec(a.width);null!=c&&(this.jJ.style.width=c.od);a=Ec(a.height);null!=a&&(this.jJ.style.height=a.od);this.jJ.parentElement&&(null!=c&&c.Ul||null!=a&&a.Ul)&&(this.jJ.parentElement.style.display="block")}};
var Ic=function(a,c,f,g,h,l,n){zc.call(this,a,c,f,g,Jc,h,l,n);this.url=a;this.o_=null;this.xA=gc();Bc(this,function(){this.Pb("beforeparentopen");var a=_.sc(this.methods);a._onopen=this.UK;a._ready=this.Jg;a._onclose=this.TK;this.params._methods=_.tc(a,"..",this.xA,this,!0);a={};for(f in this.params)a[f]=ic(this.params[f]);var c=this.config.url;if(this.DW.hideUrlFromParent){var f=window.name;var g=c;c=_.yg(this.config.url,this.params,{},ic);var h=a;a={};a._methods=h._methods;a["#opener"]=h["#opener"];
a["#urlindex"]=h["#urlindex"];a["#opener"]&&void 0!=h["#urlindex"]?(a["#opener"]=f+","+a["#opener"],f=g):(g=_.Ka(_.bb,"fUrl",[]),h=g.length,g[h]=c,_.bb.rUrl=ec,a["#opener"]=f,a["#urlindex"]=h,f=_.Rb.Pq(_.ta.location.href),c=_.P("iframes/relay_url_"+(0,window.encodeURIComponent)(f))||"/_/gapi/sibling/1/frame.html",f+=c);c=f}_.Sb._open({url:c,openParams:this.DW,params:a,proxyId:this.xA,openedByProxyChain:this.dj})})};yc(Ic);Ic.prototype.lfa=function(){return this.o_};
Ic.prototype.UK=function(a){this.o_=a.childId;var c=uc(a,"..",this.o_);_.sc(c,this);this.close=c._toclose;_.V.Uc[this.o_]=this;this.ya&&this.methods._onopen&&(a._methods=_.tc(c,this.ya.Hh(),this.o_,this,!1),this.methods._onopen(a))};Ic.prototype.Jg=function(a){var c=String(this.o_),f=uc(a,"..",c);_.sc(a,this);_.sc(f,this);this.Pb("ready",a);this.ya&&this.methods._ready&&(a._methods=_.tc(f,this.ya.Hh(),c,this,!1),this.methods._ready(a))};
Ic.prototype.TK=function(a){if(this.ya&&this.methods._onclose)this.methods._onclose(a);else return a=this.Pb("close",a),delete _.V.Uc[this.o_],a};
var Kc=function(a,c,f,g,h,l,n){zc.call(this,a,c,f,g,Jc,l,n);this.id=c.id||gc();this.oia=h;g._close=this.close;this.onClosed=this.Cba;this.DF=0;Bc(this,function(){this.Pb("beforeparentopen");var c=_.sc(this.methods);this.params._methods=_.tc(c,"..",this.xA,this,!0);c={};c.queryParams=this.params;a=_.qa(_.ua,this.config.url,this.id,c);var f=h.openWindow(a);this.canAutoClose=function(a){a(h.jj(f))};h.Tm(f,this);this.DF=f})};yc(Kc);
Kc.prototype.close=function(a){a=this.Pb("close",a);this.oia.rk(this.DF);return a};Kc.prototype.Cba=function(){this.Pb("close")};
(function(){_.V.Uc={};_.V.yf={};_.V.XR={};_.V.Kl=0;_.V.Rg={};_.V.uW={};_.V.Ng=null;_.V.Mg=[];_.V.Lr=function(a){var c=!1;try{if(null!=a){var f=window.parent.frames[a.id];c=f.iframer.id==a.id&&f.iframes.openedId_(_.Sb.id)}}catch(l){}try{_.V.Ng={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:c};for(a=0;a<_.V.Mg.length;++a)_.V.Mg[a](_.V.Ng);_.V.Mg=[]}catch(l){bG(l)}};_.V.UI=function(a){var c=a&&a.ya,f=null;c&&(f={},f.id=c.Hh(),f.proxyChain=
a.dj);return f};iH();if(window.parent!=window){var a=_.R.Qc();a.gcv&&oc(a.gcv);var c=a.jsh;c&&qc(c);_.sc(uc(a,"..",""),_.Sb);_.sc(a,_.Sb);ac()}_.V.Cr=Mc;_.V.Mo=Nc;_.V.xs=Qc;_.V.resize=Oc;_.V.Rp=function(a){return _.V.XR[a]};_.V.qj=function(a,c){_.V.XR[a]=c};_.V.rD=Oc;_.V.Ds=Qc;_.V.ng={};_.V.ng.get=Mc;_.V.ng.set=Nc;_.V.Zo=function(a,c){Zb(a);_.V.uW[a]=c||window[a]};_.V.Mt=function(a){delete _.V.uW[a]};_.V.open=function(a,c,h,l,n,q){3==arguments.length?l={}:4==arguments.length&&"function"===typeof l&&
(n=l,l={});var f="bubble"===c.style&&Pc?Pc.ma():null;return f?new Kc(a,c,h,l,f,n,q):vc(c)?new Ic(a,c,h,l,n,q):new Gc(a,c,h,l,n,q)};_.V.close=function(a,c){_.Sb&&_.Sb._close&&_.Sb._close(a,c)};_.V.ready=function(a,c,h){2==arguments.length&&"function"===typeof c&&(h=c,c={});var f=a||{};"height"in f||(f.height=_.Ob.Cd());f._methods=_.tc(c||{},"..","",_.Sb,!0);_.Sb&&_.Sb._ready&&_.Sb._ready(f,h)};_.V.Pk=function(a){_.V.Ng?a(_.V.Ng):_.V.Mg.push(a)};_.V.Ir=function(a){return!!_.V.Uc[a]};_.V.Vp=function(){return["https://ssl.gstatic.com/gb/js/",
_.P("googleapis.config/gcv")].join("")};_.V.Qr=function(a){var c={mouseover:1,mouseout:1};if(_.Sb._event)for(var f=0;f<a.length;f++){var l=a[f];l in c&&_.R.Ee(window.document,l,function(a){_.Sb._event({event:a.type,timestamp:(new Date).getTime()})},!0)}};_.V.zs=qc;_.V.NT=hG;_.V.kr=bG;_.V.dE=_.Sb})();
_.Mu("iframes.allow",_.V.Zo);_.Mu("iframes.callSiblingOpener",_.V.ip);_.Mu("iframes.registerForOpenedSibling",_.V.Sr);_.Mu("iframes.close",_.V.close);_.Mu("iframes.getGoogleConnectJsUri",_.V.Vp);_.Mu("iframes.getHandler",_.V.Cr);_.Mu("iframes.getDeferredHandler",_.V.Rp);_.Mu("iframes.getParentInfo",_.V.Pk);_.Mu("iframes.iframer",_.V.dE);_.Mu("iframes.open",_.V.open);_.Mu("iframes.openedId_",_.V.Ir);_.Mu("iframes.propagate",_.V.Qr);_.Mu("iframes.ready",_.V.ready);_.Mu("iframes.resize",_.V.resize);
_.Mu("iframes.setGoogleConnectJsVersion",_.V.xs);_.Mu("iframes.setBootstrapHint",_.V.NT);_.Mu("iframes.setJsHint",_.V.zs);_.Mu("iframes.setHandler",_.V.Mo);_.Mu("iframes.setDeferredHandler",_.V.qj);_.Mu("IframeBase",zc);_.Mu("IframeBase.prototype.addCallback",zc.prototype.zh);_.Mu("IframeBase.prototype.getMethods",zc.prototype.LW);_.Mu("IframeBase.prototype.getOpenerIframe",zc.prototype.ua);_.Mu("IframeBase.prototype.getOpenParams",zc.prototype.va);_.Mu("IframeBase.prototype.getParams",zc.prototype.tb);
_.Mu("IframeBase.prototype.removeCallback",zc.prototype.Ub);_.Mu("Iframe",Gc);_.Mu("Iframe.prototype.close",Gc.prototype.close);_.Mu("Iframe.prototype.exposeMethod",Gc.prototype.fg);_.Mu("Iframe.prototype.getId",Gc.prototype.Hh);_.Mu("Iframe.prototype.getIframeEl",Gc.prototype.rb);_.Mu("Iframe.prototype.getSiteEl",Gc.prototype.V);_.Mu("Iframe.prototype.openInto",Gc.prototype.Pa);_.Mu("Iframe.prototype.remove",Gc.prototype.remove);_.Mu("Iframe.prototype.setSiteEl",Gc.prototype.qc);
_.Mu("Iframe.prototype.addCallback",Gc.prototype.zh);_.Mu("Iframe.prototype.getMethods",Gc.prototype.LW);_.Mu("Iframe.prototype.getOpenerIframe",Gc.prototype.ua);_.Mu("Iframe.prototype.getOpenParams",Gc.prototype.va);_.Mu("Iframe.prototype.getParams",Gc.prototype.tb);_.Mu("Iframe.prototype.removeCallback",Gc.prototype.Ub);_.Mu("IframeProxy",Ic);_.Mu("IframeProxy.prototype.getTargetIframeId",Ic.prototype.lfa);_.Mu("IframeProxy.prototype.addCallback",Ic.prototype.zh);
_.Mu("IframeProxy.prototype.getMethods",Ic.prototype.LW);_.Mu("IframeProxy.prototype.getOpenerIframe",Ic.prototype.ua);_.Mu("IframeProxy.prototype.getOpenParams",Ic.prototype.va);_.Mu("IframeProxy.prototype.getParams",Ic.prototype.tb);_.Mu("IframeProxy.prototype.removeCallback",Ic.prototype.Ub);_.Mu("IframeWindow",Kc);_.Mu("IframeWindow.prototype.close",Kc.prototype.close);_.Mu("IframeWindow.prototype.onClosed",Kc.prototype.Cba);_.Mu("iframes.util.getTopMostAccessibleWindow",_.V.Kh.Uk); _.Mu("iframes.handlers.get",_.V.ng.get);_.Mu("iframes.handlers.set",_.V.ng.set);_.Mu("iframes.resizeMe",_.V.rD);_.Mu("iframes.setVersionOverride",_.V.Ds);
zc.prototype.send=function(a,c,f){_.V.Gr(this,a,c,f)};_.Sb.send=function(a,c,f){_.V.Gr(_.Sb,a,c,f)};zc.prototype.register=function(a,c){var f=this;f.zh(a,function(a){c.call(f,a)})};_.V.Gr=function(a,c,f,g){var h=[];void 0!==f&&h.push(f);g&&h.push(function(a){g.call(this,[a])});a[c]&&a[c].apply(a,h)};_.V.Fa=function(){return!0};_.Mu("iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.V.Fa);_.Mu("IframeBase.prototype.send",zc.prototype.send);_.Mu("IframeBase.prototype.register",zc.prototype.register);
_.Mu("Iframe.prototype.send",Gc.prototype.send);_.Mu("Iframe.prototype.register",Gc.prototype.register);_.Mu("IframeProxy.prototype.send",Ic.prototype.send);_.Mu("IframeProxy.prototype.register",Ic.prototype.register);_.Mu("IframeWindow.prototype.send",Kc.prototype.send);_.Mu("IframeWindow.prototype.register",Kc.prototype.register);_.Mu("iframes.iframer.send",_.V.dE.send);

var LQ=_.V.Mo,MQ={open:function(a){var c=_.bf(a.va());return a.Pa(c,{style:_.gf(c)})},attach:function(a,c){var f=_.bf(a.va()),g=c.id,h=c.getAttribute("data-postorigin")||c.src,l=/#(?:.*&)?rpctoken=(\d+)/.exec(h);l=l&&l[1];a.id=g;a.J2=l;a.el=f;a.jJ=c;_.V.Uc[g]=a;c=_.sc(a.methods);c._ready=a.Jg;c._close=a.close;c._open=a.T4;c._resizeMe=a.w0;c._renderstart=a.PA;_.tc(c,g,"",a,!0);_.T.Wg(a.id,a.J2);_.T.Xg(a.id,h);f=_.V.Wp({style:_.gf(f)});for(var n in f)Object.prototype.hasOwnProperty.call(f,n)&&("style"== n?a.jJ.style.cssText=f[n]:a.jJ.setAttribute(n,f[n]))}};MQ.onready=_.hf;MQ.onRenderStart=_.hf;MQ.close=_.jf;LQ("inline",MQ);

_.At=(window.gapi||{}).load;
_.Uo=_.r();
_.Uu=function(a){var c=window;a=(a||c.location.href).match(/.*(\?|#|&)usegapi=([^&#]+)/)||[];return"1"===(0,window.decodeURIComponent)(a[a.length-1]||"")};
var kb,rh,$g,$u,Zu,dC,Xc,Yc;kb=function(a){if(_.Ia.test(Object.keys))return Object.keys(a);var c=[],f;for(f in a)_.Qa(a,f)&&c.push(f);return c};rh=function(a,c){if(!_.Ma())try{a()}catch(f){}_.Wa(c)};$g={button:!0,div:!0,span:!0};$u=function(a){var c=_.Ka(_.bb,"sws",[]);return 0<=_.xd.call(c,a)};Zu=function(a){return _.Ka(_.bb,"watt",_.r())[a]};dC=function(a){return function(c,f){return a?_.ql()[f]||a[f]||"":_.ql()[f]||""}};
_.Vu={apppackagename:1,callback:1,clientid:1,cookiepolicy:1,openidrealm:-1,includegrantedscopes:-1,requestvisibleactions:1,scope:1};_.Wu=!1;
_.Xu=function(){if(!_.Wu){for(var a=window.document.getElementsByTagName("meta"),c=0;c<a.length;++c){var f=a[c].name.toLowerCase();if(_.jd(f,"google-signin-")){f=f.substring(14);var g=a[c].content;_.Vu[f]&&g&&(_.Uo[f]=g)}}if(window.self!==window.top){a=window.document.location.toString();for(var h in _.Vu)0<_.Vu[h]&&(c=_.e(a,h,""))&&(_.Uo[h]=c)}_.Wu=!0}h=_.r();_.Sl(_.Uo,h);return h};Xc=function(a){var c;a.match(/^https?%3A/i)&&(c=(0,window.decodeURIComponent)(a));return _.vg(window.document,c?c:a)};
Yc=function(a){a=a||"canonical";for(var c=window.document.getElementsByTagName("link"),f=0,g=c.length;f<g;f++){var h=c[f],l=h.getAttribute("rel");if(l&&l.toLowerCase()==a&&(h=h.getAttribute("href"))&&(h=Xc(h))&&null!=h.match(/^https?:\/\/[\w\-_\.]+/i))return h}return window.location.href};_.md=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};_.Zc=function(a,c,f,g){return(a="string"==typeof a?a:void 0)?Xc(a):Yc(g)}; _.fd=function(a,c,f){null==a&&f&&(a=f.db,null==a&&(a=f.gwidget&&f.gwidget.db));return a||void 0};_.gd=function(a,c,f){null==a&&f&&(a=f.ecp,null==a&&(a=f.gwidget&&f.gwidget.ecp));return a||void 0};
_.ld=function(a,c,f){return _.Zc(a,c,f,c.action?void 0:"publisher")};var Wo,av,Md,Ld,id,Gd,bv,nd;Wo={se:"0"};av={post:!0};Md={style:"position:absolute;top:-10000px;width:450px;margin:0px;border-style:none"};Ld="onPlusOne _ready _close _open _resizeMe _renderstart oncircled drefresh erefresh".split(" ");id=_.Ka(_.bb,"WI",_.r());Gd=["style","data-gapiscan"];
bv=function(a){for(var c=_.r(),f=0!=a.nodeName.toLowerCase().indexOf("g:"),g=0,h=a.attributes.length;g<h;g++){var l=a.attributes[g],n=l.name,q=l.value;0<=_.xd.call(Gd,n)||f&&0!=n.indexOf("data-")||"null"===q||"specified"in l&&!l.specified||(f&&(n=n.substr(5)),c[n.toLowerCase()]=q)}a=a.style;(f=nd(a&&a.height))&&(c.height=String(f));(a=nd(a&&a.width))&&(c.width=String(a));return c};
_.cv=function(a,c,f,g,h,l){if(f.rd)var n=c;else n=window.document.createElement("div"),c.setAttribute("data-gapistub",!0),n.style.cssText="position:absolute;width:450px;left:-10000px;",c.parentNode.insertBefore(n,c);l.siteElement=n;n.id||(n.id=_.di(a));c=_.r();c[">type"]=a;_.Sl(f,c);a=_.tb(g,n,h);l.iframeNode=a;l.id=a.getAttribute("id")};_.di=function(a){_.Ka(id,a,0);return"___"+a+"_"+id[a]++};nd=function(a){var c=void 0;"number"===typeof a?c=a:"string"===typeof a&&(c=(0,window.parseInt)(a,10));return c};
var Ak=function(){},Fk=function(a){var c=a.Ws,f=function(a){f.T.constructor.call(this,a);var c=this.Ya.length;this.dJ=[];for(var g=0;g<c;++g)this.Ya[g].zK||(this.dJ[g]=new this.Ya[g](a))};_.J(f,c);for(var g=[];a;){if(c=a.Ws){c.Ya&&_.Gl(g,c.Ya);var h=c.prototype,l;for(l in h)if(h.hasOwnProperty(l)&&_.vd(h[l])&&h[l]!==c){var n=!!h[l].RH,q=eq(l,h,g,n);(n=Dk(l,h,q,n))&&(f.prototype[l]=n)}}a=a.T&&a.T.constructor}f.prototype.Ya=g;return f},eq=function(a,c,f,g){for(var h=[],l=0;l<f.length&&(f[l].prototype[a]===
c[a]||(h.push(l),!g));++l);return h},Dk=function(a,c,f,g){return f.length?g?function(c){var g=this.dJ[f[0]];return g?g[a].apply(this.dJ[f[0]],arguments):this.Ya[f[0]].prototype[a].apply(this,arguments)}:c[a].uH?function(c){a:{var g=Array.prototype.slice.call(arguments,0);for(var h=0;h<f.length;++h){var q=this.dJ[f[h]];if(q=q?q[a].apply(q,g):this.Ya[f[h]].prototype[a].apply(this,g)){g=q;break a}}g=!1}return g}:c[a].VF?function(c){a:{var g=Array.prototype.slice.call(arguments,0);for(var h=0;h<f.length;++h){var q=
this.dJ[f[h]];q=q?q[a].apply(q,g):this.Ya[f[h]].prototype[a].apply(this,g);if(null!=q){g=q;break a}}g=void 0}return g}:c[a].AE?function(c){for(var g=Array.prototype.slice.call(arguments,0),h=0;h<f.length;++h){var q=this.dJ[f[h]];q?q[a].apply(q,g):this.Ya[f[h]].prototype[a].apply(this,g)}}:function(c){for(var g=Array.prototype.slice.call(arguments,0),h=[],q=0;q<f.length;++q){var t=this.dJ[f[q]];h.push(t?t[a].apply(t,g):this.Ya[f[q]].prototype[a].apply(this,g))}return h}:g||c[a].uH||c[a].VF||c[a].AE? null:Fm},Fm=function(){return[]};Ak.prototype.V6=function(a){if(this.dJ)for(var c=0;c<this.dJ.length;++c)if(this.dJ[c]instanceof a)return this.dJ[c];return null};
var Nn=function(a){return this.Vx.V6(a)};var Bd,Cd,Dd,Fd,dv=/(?:^|\s)g-((\S)*)(?:$|\s)/,ev={plusone:!0,autocomplete:!0,profile:!0,signin:!0,signin2:!0};Bd=_.Ka(_.bb,"SW",_.r());Cd=_.Ka(_.bb,"SA",_.r());Dd=_.Ka(_.bb,"SM",_.r());Fd=_.Ka(_.bb,"FW",[]);
var hv=function(a,c){var f;yd.ps0=(new Date).getTime();Ad("ps0");a=("string"===typeof a?window.document.getElementById(a):a)||_.ua;var g=_.ua.documentMode;if(a.querySelectorAll&&(!g||8<g)){g=c?[c]:kb(Bd).concat(kb(Cd)).concat(kb(Dd));for(var h=[],l=0;l<g.length;l++){var n=g[l];h.push(".g-"+n,"g\\:"+n)}g=a.querySelectorAll(h.join(","))}else g=a.getElementsByTagName("*");a=_.r();for(h=0;h<g.length;h++){l=g[h];var q=l;n=c;var t=q.nodeName.toLowerCase(),v=void 0;if(q.getAttribute("data-gapiscan"))n=null;
else{var w=t.indexOf("g:");0==w?v=t.substr(2):(w=(w=String(q.className||q.getAttribute("class")))&&dv.exec(w))&&(v=w[1]);n=!v||!(Bd[v]||Cd[v]||Dd[v])||n&&v!==n?null:v}n&&(ev[n]||0==l.nodeName.toLowerCase().indexOf("g:")||0!=kb(bv(l)).length)&&(l.setAttribute("data-gapiscan",!0),_.Ka(a,n,[]).push(l))}for(A in a)Fd.push(A);yd.ps1=(new Date).getTime();Ad("ps1");if(c=Fd.join(":"))try{_.Ua.load(c,void 0)}catch(F){_.kd(F);return}h=[];for(f in a){g=a[f];var A=0;for(c=g.length;A<c;A++)l=g[A],Hd(f,l,bv(l), h,c)}};
var Id=function(a,c){var f=Zu(a);c&&f?(f(c),(f=c.iframeNode)&&f.setAttribute("data-gapiattached",!0)):_.Ua.load(a,function(){var f=Zu(a),h=c&&c.iframeNode,l=c&&c.userParams;h&&f?(f(c),h.setAttribute("data-gapiattached",!0)):(f=_.Ua[a].go,"signin2"==a?f(h,l):f(h&&h.parentNode,l))})},Hd=function(a,c,f,g,h,l,n){switch(Jd(c,a,l)){case 0:a=Dd[a]?a+"_annotation":a;g={};g.iframeNode=c;g.userParams=f;Id(a,g);break;case 1:if(c.parentNode){for(var q in f){if(l=_.Qa(f,q))l=f[q],l=!!l&&"object"===typeof l&&(!l.toString||
l.toString===Object.prototype.toString||l.toString===Array.prototype.toString);if(l)try{f[q]=_.mf(f[q])}catch(K){delete f[q]}}q=!0;f.dontclear&&(q=!1);delete f.dontclear;var t;l={};var v=t=a;"plus"==a&&f.action&&(t=a+"_"+f.action,v=a+"/"+f.action);(t=_.P("iframes/"+t+"/url"))||(t=":im_socialhost:/:session_prefix::im_prefix:_/widget/render/"+v+"?usegapi=1");for(w in Wo)l[w]=w+"/"+(f[w]||Wo[w])+"/";var w=_.vg(_.ua,t.replace(_.nc,dC(l)));v="iframes/"+a+"/params/";l={};_.Sl(f,l);(t=_.P("lang")||_.P("gwidget/lang"))&&
(l.hl=t);av[a]||(l.origin=_.md());l.exp=_.P(v+"exp");if(v=_.P(v+"location"))for(t=0;t<v.length;t++){var A=v[t];l[A]=_.ta.location[A]}switch(a){case "plus":case "follow":l.url=_.ld(l.href,f,null);delete l.href;break;case "plusone":v=(v=f.href)?Xc(v):Yc();l.url=v;l.db=_.fd(f.db,void 0,_.P());l.ecp=_.gd(f.ecp,void 0,_.P());delete l.href;break;case "signin":l.url=Yc()}_.bb.ILI&&(l.iloader="1");delete l["data-onload"];delete l.rd;for(var F in Wo)l[F]&&delete l[F];l.gsrc=_.P("iframes/:source:");F=_.P("inline/css");
"undefined"!==typeof F&&0<h&&F>=h&&(l.ic="1");F=/^#|^fr-/;h={};for(var z in l)_.Qa(l,z)&&F.test(z)&&(h[z.replace(F,"")]=l[z],delete l[z]);z="q"==_.P("iframes/"+a+"/params/si")?l:h;F=_.Xu();for(var I in F)!_.Qa(F,I)||_.Qa(l,I)||_.Qa(h,I)||(z[I]=F[I]);I=[].concat(Ld);z=_.P("iframes/"+a+"/methods");_.cb(z)&&(I=I.concat(z));for(E in f)_.Qa(f,E)&&/^on/.test(E)&&("plus"!=a||"onconnect"!=E)&&(I.push(E),delete l[E]);delete l.callback;h._methods=I.join(",");var E=_.yg(w,l,h);I=n||{};I.allowPost=1;I.attributes=
Md;I.dontclear=!q;n={};n.userParams=f;n.url=E;n.type=a;_.cv(a,c,f,E,I,n);c=n.id;f=_.r();f.id=c;f.userParams=n.userParams;f.url=n.url;f.type=n.type;f.state=1;_.Tc[c]=f;c=n}else c=null;c&&((f=c.id)&&g.push(f),Id(a,c))}},Jd=function(a,c,f){if(a&&1===a.nodeType&&c){if(f)return 1;if(Dd[c]){if($g[a.nodeName.toLowerCase()])return(a=a.innerHTML)&&a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")?0:1}else{if(Cd[c])return 0;if(Bd[c])return 1}}return null};
_.Ka(_.Ua,"platform",{}).go=function(a,c){hv(a,c)};var Rd=_.Ka(_.bb,"perf",_.r()),yd=_.Ka(Rd,"g",_.r()),Ud=_.Ka(Rd,"i",_.r()),Pd,Qd,Od,Ad,Sd,Td,Vd;_.Ka(Rd,"r",[]);Pd=_.r();Qd=_.r();Od=function(a,c,f,g){Pd[f]=Pd[f]||!!g;_.Ka(Qd,f,[]);Qd[f].push([a,c])};Ad=function(a,c,f){var g=Rd.r;"function"===typeof g?g(a,c,f):g.push([a,c,f])};Sd=function(a,c,f,g){if("_p"==c)throw Error("Ra");_.nf(a,c,f,g)};_.nf=function(a,c,f,g){Td(c,f)[a]=g||(new Date).getTime();Ad(a,c,f)};Td=function(a,c){a=_.Ka(Ud,a,_.r());return _.Ka(a,c,_.r())}; Vd=function(a,c,f){var g=null;c&&f&&(g=Td(c,f)[a]);return g||yd[a]};
(function(){function a(a){this.t={};this.tick=function(a,c,f){this.t[a]=[void 0!=f?f:(new Date).getTime(),c];if(void 0==f)try{window.console.timeStamp("CSI/"+a)}catch(w){}};this.tick("start",null,a)}var c;if(window.performance)var f=(c=window.performance.timing)&&c.responseStart;var g=0<f?new a(f):new a;window.__gapi_jstiming__={Timer:a,load:g};if(c){var h=c.navigationStart;0<h&&f>=h&&(window.__gapi_jstiming__.srt=f-h)}if(c){var l=window.__gapi_jstiming__.load;0<h&&f>=h&&(l.tick("_wtsrt",void 0,h),
l.tick("wtsrt_","_wtsrt",f),l.tick("tbsd_","wtsrt_"))}try{c=null,window.chrome&&window.chrome.csi&&(c=Math.floor(window.chrome.csi().pageT),l&&0<h&&(l.tick("_tbnd",void 0,window.chrome.csi().startE),l.tick("tbnd_","_tbnd",h))),null==c&&window.gtbExternal&&(c=window.gtbExternal.pageT()),null==c&&window.external&&(c=window.external.pageT,l&&0<h&&(l.tick("_tbnd",void 0,window.external.startE),l.tick("tbnd_","_tbnd",h))),c&&(window.__gapi_jstiming__.pt=c)}catch(n){}})();
if(window.__gapi_jstiming__){window.__gapi_jstiming__.Pz={};window.__gapi_jstiming__.Yr=1;var he=function(a,c,f){var g=a.t[c],h=a.t.start;if(g&&(h||f))return g=a.t[c][0],h=void 0!=f?f:h[0],Math.round(g-h)};window.__gapi_jstiming__.getTick=he;window.__gapi_jstiming__.getLabels=function(a){var c=[],f;for(f in a.t)c.push(f);return c};var ie=function(a,c,f){var g="";window.__gapi_jstiming__.srt&&(g+="&srt="+window.__gapi_jstiming__.srt);window.__gapi_jstiming__.pt&&(g+="&tbsrt="+window.__gapi_jstiming__.pt);
try{window.external&&window.external.tran?g+="&tran="+window.external.tran:window.gtbExternal&&window.gtbExternal.tran?g+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(g+="&tran="+window.chrome.csi().tran)}catch(A){}var h=window.chrome;if(h&&(h=h.loadTimes)){h().wasFetchedViaSpdy&&(g+="&p=s");if(h().wasNpnNegotiated){g+="&npn=1";var l=h().npnNegotiatedProtocol;l&&(g+="&npnv="+(window.encodeURIComponent||window.escape)(l))}h().wasAlternateProtocolAvailable&&(g+="&apa=1")}var n=
a.t,q=n.start;h=[];l=[];for(var t in n)if("start"!=t&&0!=t.indexOf("_")){var v=n[t][1];v?n[v]&&l.push(t+"."+he(a,t,n[v][0])):q&&h.push(t+"."+he(a,t))}if(c)for(var w in c)g+="&"+w+"="+c[w];(c=f)||(c="https:"==window.document.location.protocol?"https://csi.gstatic.com/csi":"http://csi.gstatic.com/csi");return[c,"?v=3","&s="+(window.__gapi_jstiming__.sn||"oz")+"&action=",a.name,l.length?"&it="+l.join(","):"",g,"&rt=",h.join(",")].join("")},je=function(a,c,f){a=ie(a,c,f);if(!a)return"";c=new window.Image;
var g=window.__gapi_jstiming__.Yr++;window.__gapi_jstiming__.Pz[g]=c;c.onload=c.onerror=function(){window.__gapi_jstiming__&&delete window.__gapi_jstiming__.Pz[g]};c.src=a;c=null;return a};window.__gapi_jstiming__.report=function(a,c,f){var g=window.document.visibilityState,h="visibilitychange";g||(g=window.document.webkitVisibilityState,h="webkitvisibilitychange");if("prerender"==g){var l=!1,n=function(){if(!l){c?c.prerender="1":c={prerender:"1"};if("prerender"==(window.document.visibilityState|| window.document.webkitVisibilityState))var g=!1;else je(a,c,f),g=!0;g&&(l=!0,window.document.removeEventListener(h,n,!1))}};window.document.addEventListener(h,n,!1);return""}return je(a,c,f)}};
var ee={g:"gapi_global",m:"gapi_module",w:"gwidget"},Wd=function(a,c){this.type=a?"_p"==a?"m":"w":"g";this.name=a;this.P0=c};Wd.prototype.key=function(){switch(this.type){case "g":return this.type;case "m":return this.type+"."+this.P0;case "w":return this.type+"."+this.name+this.P0}};
var ce=new Wd,Yd=window.navigator.userAgent.match(/iPhone|iPad|Android|PalmWebOS|Maemo|Bada/),$d=_.Ka(Rd,"_c",_.r()),ae=Math.random()<(_.P("csi/rate")||0),Zd=function(a,c,f){for(var g=new Wd(c,f),h=_.Ka($d,g.key(),_.r()),l=Qd[a]||[],n=0;n<l.length;++n){var q=l[n],t=q[0],v=a,w=c,A=f;q=Vd(q[1],w,A);v=Vd(v,w,A);h[t]=q&&v?v-q:null}Pd[a]&&ae&&(be(ce),be(g))},de=function(a,c){c=c||[];for(var f=[],g=0;g<c.length;g++)f.push(a+c[g]);return f},be=function(a){var c=_.ta.__gapi_jstiming__;c.sn=ee[a.type];var f=
new c.Timer(0);a:{switch(a.type){case "g":var g="global";break a;case "m":g=a.P0;break a;case "w":g=a.name;break a}g=void 0}f.name=g;g=!1;var h=a.key(),l=$d[h];f.tick("_start",null,0);for(var n in l)f.tick(n,"_start",l[n]),g=!0;$d[h]=_.r();g&&(n=[],n.push("l"+(_.P("isPlusUser")?"1":"0")),g="m"+(Yd?"1":"0"),n.push(g),"m"==a.type?n.push("p"+a.P0):"w"==a.type&&(h="n"+a.P0,n.push(h),"0"==a.P0&&n.push(g+h)),n.push("u"+(_.P("isLoggedIn")?"1":"0")),a=de("",n),a=de("abc_",a).join(","),c.report(f,{e:a}))};
Od("blt","bs0","bs1");Od("psi","ps0","ps1");Od("rpcqi","rqe","rqd");Od("bsprt","bsrt0","bsrt1");Od("bsrqt","bsrt1","bsrt2");Od("bsrst","bsrt2","bsrt3");Od("mli","ml0","ml1");Od("mei","me0","me1",!0);Od("wcdi","wrs","wcdi");Od("wci","wrs","wdc");Od("wdi","wrs","wrdi");Od("wdt","bs0","wrdt");Od("wri","wrs","wrri",!0);Od("wrt","bs0","wrrt");Od("wji","wje0","wje1",!0);Od("wjli","wjl0","wjl1");Od("whi","wh0","wh1",!0);Od("wai","waaf0","waaf1",!0);Od("wadi","wrs","waaf1",!0);Od("wadt","bs0","waaf1",!0);
Od("wprt","wrt0","wrt1");Od("wrqt","wrt1","wrt2");Od("wrst","wrt2","wrt3",!0);Od("fbprt","fsrt0","fsrt1");Od("fbrqt","fsrt1","fsrt2");Od("fbrst","fsrt2","fsrt3",!0);Od("fdns","fdns0","fdns1");Od("fcon","fcon0","fcon1");Od("freq","freq0","freq1");Od("frsp","frsp0","frsp1");Od("fttfb","fttfb0","fttfb1");Od("ftot","ftot0","ftot1",!0);var QP=Rd.r;if("function"!==typeof QP){for(var RP;RP=QP.shift();)Zd.apply(null,RP);Rd.r=Zd};
var Rt=["div"],jC="onload",zx=!0,cB=!0,gg=function(a){return a},gC=null,Kg=function(a){var c=_.P(a);return"undefined"!==typeof c?c:_.P("gwidget/"+a)},uv,vv,Cv,Dv,Tt,sw,Ev,Ut,eC,fC,hC,Fv;gC=_.P();_.P("gwidget");var bQ=Kg("parsetags");jC="explicit"===bQ||"onload"===bQ?bQ:jC;var rQ=Kg("google_analytics");"undefined"!==typeof rQ&&(zx=!!rQ);var BQ=Kg("data_layer");"undefined"!==typeof BQ&&(cB=!!BQ);
var ov=function(){var a=this&&this.Hh();a&&(_.bb.drw=a)},pv=function(){_.bb.drw=null},Uj=function(a){return function(c){var f=a;"number"===typeof c?f=c:"string"===typeof c&&(f=c.indexOf("px"),-1!=f&&(c=c.substring(0,f)),f=(0,window.parseInt)(c,10));return f}},En=function(a){"string"===typeof a&&(a=window[a]);return"function"===typeof a?a:null},Ft=function(){return Kg("lang")||"en-US"},It=function(a){if(!_.V.Cr("attach")){var c={},f=_.V.Cr("inline"),g;for(g in f)f.hasOwnProperty(g)&&(c[g]=f[g]);c.open=
function(a){var c=a.va().renderData.id;c=window.document.getElementById(c);if(!c)throw Error("o");return f.attach(a,c)};_.V.Mo("attach",c)}a.style="attach"},Mt=function(){var a={};a.width=[Uj(450)];a.height=[Uj(24)];a.onready=[En];a.lang=[Ft,"hl"];a.iloader=[function(){return _.bb.ILI},"iloader"];return a}(),Jt=function(a){var c={};c.Fb=a[0];c.Kj=-1;c.ZX="___"+c.Fb+"_";c.Xs="g:"+c.Fb;c.Wt="g-"+c.Fb;c.Dm=[];c.config={};c.jd=[];c.Rh={};c.Ie={};var f=function(a){for(var f in a)if(_.Qa(a,f)){c.config[f]=
[En];c.jd.push(f);var g=a[f],h=null,t=null,v=null;"function"===typeof g?h=g:g&&"object"===typeof g&&(h=g.Er,t=g.Kg,v=g.Qh);v&&(c.jd.push(v),c.config[v]=[En],c.Rh[f]=v);h&&(c.config[f]=[h]);t&&(c.Ie[f]=t)}},g=function(a){for(var f={},g=0;g<a.length;++g)f[a[g].toLowerCase()]=1;f[c.Xs]=1;c.nr=f};a[1]&&(c.parameters=a[1]);(function(a){c.config=a;for(var f in Mt)Mt.hasOwnProperty(f)&&!c.config.hasOwnProperty(f)&&(c.config[f]=Mt[f])})(a[2]||{});a[3]&&f(a[3]);a[4]&&g(a[4]);a[5]&&(c.qe=a[5]);c.nu=!0===a[6];
c.Or=a[7];c.lM=a[8];c.nr||g(Rt);c.bj=function(a){c.Kj++;Sd("wrs",c.Fb,String(c.Kj));var f=[],g=a.element,h=a.config,t=":"+c.Fb;":plus"==t&&a.Yi&&a.Yi.action&&(t+="_"+a.Yi.action);var v=St(c,h),w={};_.Sl(_.Xu(),w);for(var A in a.Yi)null!=a.Yi[A]&&(w[A]=a.Yi[A]);A={container:g.id,renderData:a.Xr,style:"inline",height:h.height,width:h.width};It(A);c.qe&&(f[2]=A,f[3]=w,f[4]=v,c.qe("i",f));t=_.V.open(t,A,w,v);qv(c,t,h,g,a.xp);f[5]=t;c.qe&&c.qe("e",f)};return c},St=function(a,c){for(var f={},g=a.jd.length-
1;0<=g;--g){var h=a.jd[g],l=c[a.Rh[h]||h]||c[h],n=c[h];n&&l!==n&&(l=function(a,c){return function(f){c.apply(this,arguments);a.apply(this,arguments)}}(l,n));l&&(f[h]=l)}for(var q in a.Ie)a.Ie.hasOwnProperty(q)&&(f[q]=tw(f[q]||function(){},a.Ie[q]));f.drefresh=ov;f.erefresh=pv;return f},tw=function(a,c){return function(f){var g=c(f);if(g){var h=f.href||null;if(zx){if(window._gat)try{var l=window._gat._getTrackerByName("~0");l&&"UA-XXXXX-X"!=l._getAccount()?l._trackSocial("Google",g,h):window._gaq&&
window._gaq.push(["_trackSocial","Google",g,h])}catch(q){}if(window.ga&&window.ga.getAll)try{var n=window.ga.getAll();for(l=0;l<n.length;l++)n[l].send("social","Google",g,h)}catch(q){}}if(cB&&window.dataLayer)try{window.dataLayer.push({event:"social",socialNetwork:"Google",socialAction:g,socialTarget:h})}catch(q){}}a.call(this,f)}},qv=function(a,c,f,g,h){Tt(c,f);Ut(c,g);sw(a,c,h);XF(a.Fb,a.Kj.toString(),c);(new Ds).Vx.Ep(a,c,f,g,h)},Ds=function(){if(!this.Vx){for(var a=this.constructor;a&&!a.Ws;)a=
a.T&&a.T.constructor;a.Ws.UD||(a.Ws.UD=Fk(a));this.Vx=new a.Ws.UD(this);this.V6||(this.V6=Nn)}},Gs=function(){},CQ=Ds;Gs.T||_.J(Gs,Ak);CQ.Ws=Gs;Gs.prototype.Ep=function(a){a=a?a:function(){};a.AE=!0;return a}();uv=function(a){return _.Rm&&"undefined"!=typeof _.Rm&&a instanceof _.Rm};vv=function(a){return uv(a)?"_renderstart":"renderstart"};Cv=function(a){return uv(a)?"_ready":"ready"};Dv=function(){return!0};
Tt=function(a,c){if(c.onready){var f=!1,g=function(){f||(f=!0,c.onready.call(null))};a.register(Cv(a),g,Dv);a.register(vv(a),g,Dv)}};
sw=function(a,c,f){var g=a.Fb,h=String(a.Kj),l=!1,n=function(){l||(l=!0,f&&Sd("wrdt",g,h),Sd("wrdi",g,h))};c.register(vv(c),n,Dv);var q=!1;a=function(){q||(q=!0,n(),f&&Sd("wrrt",g,h),Sd("wrri",g,h))};c.register(Cv(c),a,Dv);uv(c)?c.register("widget-interactive-"+c.id,a,Dv):_.T.register("widget-interactive-"+c.id,a);_.T.register("widget-csi-tick-"+c.id,function(a,c,f){"wdc"===a?Sd("wdc",g,h,f):"wje0"===a?Sd("wje0",g,h,f):"wje1"===a?Sd("wje1",g,h,f):"wh0"==a?_.nf("wh0",g,h,f):"wh1"==a?_.nf("wh1",g,h,
f):"wcdi"==a&&_.nf("wcdi",g,h,f)})};Ev=function(a){return"number"==typeof a?a+"px":"100%"==a?a:null};Ut=function(a,c){var f=function(f){f=f||a;var g=Ev(f.width);g&&c.style.width!=g&&(c.style.width=g);(f=Ev(f.height))&&c.style.height!=f&&(c.style.height=f)};uv(a)?a.Vm("onRestyle",f):(a.register("ready",f,Dv),a.register("renderstart",f,Dv),a.register("resize",f,Dv))};eC=function(a,c){for(var f in Mt)if(Mt.hasOwnProperty(f)){var g=Mt[f][1];g&&!c.hasOwnProperty(g)&&(c[g]=a[g])}return c};
fC=function(a,c){var f={},g;for(g in a)a.hasOwnProperty(g)&&(f[a[g][1]||g]=(a[g]&&a[g][0]||gg)(c[g.toLowerCase()],c,gC));return f};hC=function(a){if(a=a.Or)for(var c=0;c<a.length;c++)(new window.Image).src=a[c]};Fv=function(a,c){var f=c.userParams,g=c.siteElement;g||(g=(g=c.iframeNode)&&g.parentNode);if(g&&1===g.nodeType){var h=fC(a.config,f);a.Dm.push({element:g,config:h,Yi:eC(h,fC(a.parameters,f)),Sg:3,xp:!!f["data-onload"],Xr:c})}c=a.Dm;for(a=a.bj;0<c.length;)a(c.shift())};
_.iC=function(a){var c=Jt(a);hC(c);_.Sc(c.Fb,function(a){Fv(c,a)});Bd[c.Fb]=!0;var f={S:function(a,f,l){var g=f||{};g.type=c.Fb;f=g.type;delete g.type;var h=("string"===typeof a?window.document.getElementById(a):a)||void 0;if(h){a={};for(var t in g)_.Qa(g,t)&&(a[t.toLowerCase()]=g[t]);a.rd=1;(t=!!a.ri)&&delete a.ri;Hd(f,h,a,[],0,t,l)}else _.kd("string"==="gapi."+f+".render: missing element "+typeof a?a:"")},go:function(a){hv(a,c.Fb)},zja:function(){var a=_.Ka(_.bb,"WI",_.r()),c;for(c in a)delete a[c]}}; a=function(){"onload"===jC&&f.go()};$u(c.Fb)||rh(a,a);_.Mu("gapi."+c.Fb+".go",f.go);_.Mu("gapi."+c.Fb+".render",f.S);return f};
var Gv=Fv,Hv=function(a,c){a.Kj++;Sd("wrs",a.Fb,String(a.Kj));var f=c.userParams,g=fC(a.config,f),h=[],l=c.iframeNode,n=c.siteElement,q=St(a,g),t=fC(a.parameters,f);_.Sl(_.Xu(),t);t=eC(g,t);f=!!f["data-onload"];var v=_.Sm,w=_.r();w.renderData=c;w.height=g.height;w.width=g.width;w.id=c.id;w.url=c.url;w.iframeEl=l;w.where=w.container=n;w.apis=["_open"];w.messageHandlers=q;w.messageHandlersFilter=_.Vz;_.Ru(w);l=t;a.qe&&(h[2]=w,h[3]=l,h[4]=q,a.qe("i",h));q=v.OH(w);q.id=c.id;q.NA(q,w);qv(a,q,g,n,f);h[5]= q;a.qe&&a.qe("e",h)};Fv=function(a,c){var f=c.url;a.lM||_.Uu(f)?_.jo?Hv(a,c):(0,_.At)("gapi.iframes.impl",function(){Hv(a,c)}):_.V.open?Gv(a,c):(0,_.At)("iframes",function(){Gv(a,c)})};
var Iv=function(){var a=window;return!!a.performance&&!!a.performance.getEntries},XF=function(a,c,f){if(Iv()){var g=function(){var a=!1;return function(){if(a)return!0;a=!0;return!1}}(),h=function(){g()||window.setTimeout(function(){var g=f.rb().src;var h=g.indexOf("#");-1!=h&&(g=g.substring(0,h));g=window.performance.getEntriesByName(g);1>g.length?g=null:(g=g[0],g=0==g.responseStart?null:g);if(g){h=Math.round(g.requestStart);var q=Math.round(g.responseStart),t=Math.round(g.responseEnd);Sd("wrt0", a,c,Math.round(g.startTime));Sd("wrt1",a,c,h);Sd("wrt2",a,c,q);Sd("wrt3",a,c,t)}},1E3)};f.register(vv(f),h,Dv);f.register(Cv(f),h,Dv)}};
_.Mu("gapi.widget.make",_.iC);
var Dg,To,Pv,qu,FH,vO,zH,vs,dg,eg,bg;_.eG=function(a){if(a instanceof _.NG)return a;var c="object"==typeof a,f=null;c&&a.mK&&(f=a.Im());return _.uf(_.He(c&&a.nK?a.cR():String(a)),f)};_.Ne=function(a,c){return a==c?!0:a&&c?a.x==c.x&&a.y==c.y:!1};_.X=function(a,c){this.x=_.kf(a)?a:0;this.y=_.kf(c)?c:0};_.k=_.X.prototype;_.k.clone=function(){return new _.X(this.x,this.y)};_.k.equals=function(a){return a instanceof _.X&&_.Ne(this,a)};
_.k.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};_.k.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};_.k.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};_.k.translate=function(a,c){a instanceof _.X?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),_.qe(c)&&(this.y+=c));return this};_.k.scale=function(a,c){c=_.qe(c)?c:a;this.x*=a;this.y*=c;return this};_.fg=function(a,c){this.width=a;this.height=c};
_.k=_.fg.prototype;_.k.clone=function(){return new _.fg(this.width,this.height)};_.k.Cda=function(){return this.width*this.height};_.k.aspectRatio=function(){return this.width/this.height};_.k.isEmpty=function(){return!this.Cda()};_.k.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};_.k.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
_.k.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.k.scale=function(a,c){c=_.qe(c)?c:a;this.width*=a;this.height*=c;return this};_.Lf=function(a){return"CSS1Compat"==a.compatMode};_.Ct=function(a){a=a.document;a=_.Lf(a)?a.documentElement:a.body;return new _.fg(a.clientWidth,a.clientHeight)};_.ig=function(a){return _.Ct(a||window)};_.Kf=function(a){return a.scrollingElement?a.scrollingElement:!_.ef&&_.Lf(a)?a.documentElement:a.body||a.documentElement};
_.Jf=function(a){var c=_.Kf(a);a=a.parentWindow||a.defaultView;return _.W&&_.sl("10")&&a.pageYOffset!=c.scrollTop?new _.X(c.scrollLeft,c.scrollTop):new _.X(a.pageXOffset||c.scrollLeft,a.pageYOffset||c.scrollTop)};Dg=function(a){var c=_.fa(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(new RegExp("(^"+(c?"|["+c+"]+":"")+")([a-z])","g"),function(a,c,h){return c+h.toUpperCase()})};
_.CM=function(a,c,f){if(null!==a&&c in a)throw Error("p`"+c);a[c]=f};_.Bw=function(a){if(a instanceof _.pm&&a.constructor===_.pm&&a.qda===_.nm)return a.M8;_.da(a);return"type_error:SafeStyle"};To=/\b(hsl|hsla|rgb|rgba|matrix|calc|minmax|fit-content|repeat|(rotate|scale|translate)(X|Y|Z|3d)?)\([-+*/0-9a-z.%\[\], ]+\)/g;Pv=/\b(url\([ \t\n]*)('[ -&(-\[\]-~]*'|"[ !#-\[\]-~]*"|[!#-&*-\[\]-~]*)([ \t\n]*\))/g;qu=/^[-,."'%_!# a-zA-Z0-9\[\]]+$/;FH=/\/\*/;
vO=function(a){for(var c=!0,f=/^[-_a-zA-Z0-9]$/,g=0;g<a.length;g++){var h=a.charAt(g);if("]"==h){if(c)return!1;c=!0}else if("["==h){if(!c)return!1;c=!1}else if(!c&&!f.test(h))return!1}return c};zH=function(a){return a.replace(Pv,function(a,f,g,h){var c="";g=g.replace(/^(['"])(.*)\1$/,function(a,f,g){c=f;return g});a=_.jw(g).cR();return f+c+a+c+h})};
vs=function(a){if(a instanceof _.su)a='url("'+_.Ls(a).replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';else if(a instanceof _.ou)a=_.ru(a);else{a=String(a);var c=a.replace(To,"$1").replace(To,"$1").replace(Pv,"url");if(qu.test(c)){if(c=!FH.test(a)){for(var f=c=!0,g=0;g<a.length;g++){var h=a.charAt(g);"'"==h&&f?c=!c:'"'==h&&c&&(f=!f)}c=c&&f&&vO(a)}a=c?zH(a):"zClosurez"}else a="zClosurez"}return a};
_.cp=function(a){var c="",f;for(f in a){if(!/^[-_a-zA-Z0-9]+$/.test(f))throw Error("e`"+f);var g=a[f];null!=g&&(g=_.ea(g)?(0,_.De)(g,vs).join(" "):vs(g),c+=f+":"+g+";")}return c?(new _.pm).XY(c):_.rm};_.wm=function(a){if(a instanceof _.xm&&a.constructor===_.xm&&a.pda===_.Bl)return a.L8;_.da(a);return"type_error:SafeStyleSheet"};_.KQ=function(a,c){if((0,_.Hq)())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=c};_.Ng=function(a,c,f){return _.Mf(window.document,arguments)};
_.bw=function(a){var c;if(_.Zn&&!(_.W&&_.sl("9")&&!_.sl("10")&&_.D.SVGElement&&a instanceof _.D.SVGElement)&&(c=a.parentElement))return c;c=a.parentNode;return _.iz(c)?c:null};dg={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1};eg={IMG:" ",BR:"\n"};bg=function(a,c,f){if(!(a.nodeName in dg))if(3==a.nodeType)f?c.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):c.push(a.nodeValue);else if(a.nodeName in eg)c.push(eg[a.nodeName]);else for(a=a.firstChild;a;)bg(a,c,f),a=a.nextSibling};
_.$f=function(a){if(_.ag&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var c=[];bg(a,c,!0);a=c.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");_.ag||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a};_.cg=function(a){var c=[];bg(a,c,!1);return c.join("")};
_.Pg=function(a,c,f,g){this.top=a;this.right=c;this.bottom=f;this.left=g};_.k=_.Pg.prototype;_.k.Ne=_.b(3);_.k.Cd=function(){return this.bottom-this.top};_.k.clone=function(){return new _.Pg(this.top,this.right,this.bottom,this.left)};_.k.contains=function(a){return this&&a?a instanceof _.Pg?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
_.k.expand=function(a,c,f,g){_.Vg(a)?(this.top-=a.top,this.right+=a.right,this.bottom+=a.bottom,this.left-=a.left):(this.top-=a,this.right+=Number(c),this.bottom+=Number(f),this.left-=Number(g));return this};_.k.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
_.k.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};_.k.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
_.k.translate=function(a,c){a instanceof _.X?(this.left+=a.x,this.right+=a.x,this.top+=a.y,this.bottom+=a.y):(this.left+=a,this.right+=a,_.qe(c)&&(this.top+=c,this.bottom+=c));return this};_.k.scale=function(a,c){c=_.qe(c)?c:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};
var bZ,qg,xg,zg,Sg,Rg;_.Mg=function(a,c,f){if(_.fa(c))(c=_.Fg(a,c))&&(a.style[c]=f);else for(var g in c){f=a;var h=c[g],l=_.Fg(f,g);l&&(f.style[l]=h)}};bZ={};_.Fg=function(a,c){var f=bZ[c];if(!f){var g=_.Cg(c);f=g;void 0===a.style[g]&&(g=(_.ef?"Webkit":_.df?"Moz":_.W?"ms":_.cf?"O":null)+Dg(g),void 0!==a.style[g]&&(f=g));bZ[c]=f}return f};
_.lg=function(a,c){var f=_.zf(a);return f.defaultView&&f.defaultView.getComputedStyle&&(a=f.defaultView.getComputedStyle(a,null))?a[c]||a.getPropertyValue(c)||"":""};_.mg=function(a,c){return a.currentStyle?a.currentStyle[c]:null};_.ng=function(a,c){return _.lg(a,c)||_.mg(a,c)||a.style&&a.style[c]};_.Zg=function(a,c,f){if(c instanceof _.X){var g=c.x;c=c.y}else g=c,c=f;a.style.left=xg(g,!1);a.style.top=xg(c,!1)};
qg=function(a){try{var c=a.getBoundingClientRect()}catch(f){return{left:0,top:0,right:0,bottom:0}}_.W&&a.ownerDocument.body&&(a=a.ownerDocument,c.left-=a.documentElement.clientLeft+a.body.clientLeft,c.top-=a.documentElement.clientTop+a.body.clientTop);return c};
_.Yr=function(a,c){c=c||_.Kf(window.document);var f=c||_.Kf(window.document);var g=_.sg(a),h=_.sg(f),l=_.Ug(f);if(f==_.Kf(window.document)){var n=g.x-f.scrollLeft;g=g.y-f.scrollTop;_.W&&!_.gq(10)&&(n+=l.left,g+=l.top)}else n=g.x-h.x-l.left,g=g.y-h.y-l.top;a=zg(a);l=f.clientHeight-a.height;h=f.scrollLeft;var q=f.scrollTop;h+=Math.min(n,Math.max(n-(f.clientWidth-a.width),0));q+=Math.min(g,Math.max(g-l,0));f=new _.X(h,q);c.scrollLeft=f.x;c.scrollTop=f.y};
_.sg=function(a){var c=_.zf(a),f=new _.X(0,0);var g=c?_.zf(c):window.document;g=!_.W||_.gq(9)||_.Lf(_.xf(g).wc)?g.documentElement:g.body;if(a==g)return f;a=qg(a);c=_.Jf(_.xf(c).wc);f.x=a.left+c.x;f.y=a.top+c.y;return f};_.tg=function(a,c){var f=new _.X(0,0),g=_.jg(_.zf(a));if(!_.Eo(g,"parent"))return f;do{var h=g==c?_.sg(a):_.Kt(a);f.x+=h.x;f.y+=h.y}while(g&&g!=c&&g!=g.parent&&(a=g.frameElement)&&(g=g.parent));return f};_.Kt=function(a){a=qg(a);return new _.X(a.left,a.top)};
_.wg=function(a,c,f){if(c instanceof _.fg)f=c.height,c=c.width;else if(void 0==f)throw Error("r");a.style.width=xg(c,!0);a.style.height=xg(f,!0)};xg=function(a,c){"number"==typeof a&&(a=(c?Math.round(a):a)+"px");return a};_.Nt=function(a){var c=zg;if("none"!=_.ng(a,"display"))return c(a);var f=a.style,g=f.display,h=f.visibility,l=f.position;f.visibility="hidden";f.position="absolute";f.display="inline";a=c(a);f.display=g;f.position=l;f.visibility=h;return a};
zg=function(a){var c=a.offsetWidth,f=a.offsetHeight,g=_.ef&&!c&&!f;return _.kf(c)&&!g||!a.getBoundingClientRect?new _.fg(c,f):(a=qg(a),new _.fg(a.right-a.left,a.bottom-a.top))};_.Ag=function(a,c){a=a.style;"opacity"in a?a.opacity=c:"MozOpacity"in a?a.MozOpacity=c:"filter"in a&&(a.filter=""===c?"":"alpha(opacity="+100*Number(c)+")")};_.Rj=function(a,c){a.style.display=c?"":"none"};
_.tO=function(a){var c=_.xf(void 0),f=c.Wb();if(_.W&&f.createStyleSheet)return c=f.createStyleSheet(),_.QF(c,a),c;f=_.Cf(c.wc,"HEAD",void 0,void 0)[0];if(!f){var g=_.Cf(c.wc,"BODY",void 0,void 0)[0];f=c.R("HEAD");g.parentNode.insertBefore(f,g)}g=c.R("STYLE");_.QF(g,a);c.appendChild(f,g);return g};_.QF=function(a,c){c=_.wm(c);_.W&&_.kf(a.cssText)?a.cssText=c:a.innerHTML=c};_.Eg=function(a){return"rtl"==_.ng(a,"direction")};_.Bg=_.df?"MozUserSelect":_.ef||_.yk?"WebkitUserSelect":null;
_.Qg=function(a,c){if(/^\d+px?$/.test(c))return(0,window.parseInt)(c,10);var f=a.style.left,g=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=c;c=a.style.pixelLeft;a.style.left=f;a.runtimeStyle.left=g;return+c};Sg={thin:2,medium:4,thick:6};Rg=function(a,c){if("none"==_.mg(a,c+"Style"))return 0;c=_.mg(a,c+"Width");return c in Sg?Sg[c]:_.Qg(a,c)};
_.Ug=function(a){if(_.W&&!_.gq(9)){var c=Rg(a,"borderLeft"),f=Rg(a,"borderRight"),g=Rg(a,"borderTop");a=Rg(a,"borderBottom");return new _.Pg(g,f,a,c)}c=_.lg(a,"borderLeftWidth");f=_.lg(a,"borderRightWidth");g=_.lg(a,"borderTopWidth");a=_.lg(a,"borderBottomWidth");return new _.Pg((0,window.parseFloat)(g),(0,window.parseFloat)(f),(0,window.parseFloat)(a),(0,window.parseFloat)(c))};

(function(){var a={},c=null,f=null;a[0]="ratingbadge";a[5]=function(a,h){var g=h[2].renderData.userParams.position;"e"==a&&(c=h[5],f=c.Hh());f&&(a=window.document.getElementById(f))&&a.parentNode&&(_.Mg(a,{display:"block"}),_.Mg(a.parentNode,{border:"1px solid #f5f5f5"}),"INLINE"!=g&&(_.Mg(a.parentNode,{"z-index":2147483647,position:"fixed"}),"BOTTOM_LEFT"==g?_.Mg(a.parentNode,{left:0,bottom:0,"box-shadow":"1px 1px 3px #A2A2A2"}):_.Mg(a.parentNode,{right:0,bottom:0,"box-shadow":"-1px 1px 3px #A2A2A2"})))}; _.iC(a)})();

});
// Google Inc.
