"use strict";this.shopping_verified_reviews_VerifiedReviewsGcrBootstrapJs=this.shopping_verified_reviews_VerifiedReviewsGcrBootstrapJs||{};(function(_){var window=this;
try{
var h,k=this,l=function(a){return"string"==typeof a},aa=/^[\w+/_-]+[=]{0,2}$/,n=null,p=function(a,b){a=a.split(".");b=b||k;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b},q=function(){},ba=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&
!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},r=function(a){return"function"==ba(a)},ca=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},da=function(a,b,c){return a.call.apply(a.bind,arguments)},ea=function(a,b,c){if(!a)throw Error();if(2<
arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},t=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?t=da:t=ea;return t.apply(null,arguments)},fa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,
b)}},u=Date.now||function(){return+new Date},v=function(a,b){function c(){}c.prototype=b.prototype;a.B=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.A=function(a,c,g){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
var w=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,w);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};v(w,Error);w.prototype.name="CustomError";var ha=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=l(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)};var x=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},ia=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)},y=function(a){a=String(a);var b=a.indexOf(".");-1==b&&(b=a.length);return ia("0",Math.max(0,2-b))+a},z=function(a,b){return a<b?-1:a>b?1:0},ja=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})},ka=function(a){var b=l(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g, "\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};
var la=/^(\d{4})(?:(?:-?(\d{2})(?:-?(\d{2}))?)|(?:-?(\d{3}))|(?:-?W(\d{2})(?:-?([1-7]))?))?$/,ma=/^(\d{2})(?::?(\d{2})(?::?(\d{2})(\.\d+)?)?)?$/,na=/Z|(?:([-+])(\d{2})(?::?(\d{2}))?)$/,B=function(a){l("d")?(this.f=this.h=0,this.a=a,this.g=this.c=this.b=0):(this.h="d",this.f=a||0,this.g=this.c=this.b=this.a=0)};B.prototype.add=function(a){this.h+=a.h;this.f+=a.f;this.a+=a.a;this.b+=a.b;this.c+=a.c;this.g+=a.g};
var D=function(a,b,c){"number"==typeof a?(this.a=oa(a,b||0,c||1),C(this,c||1)):ca(a)?(this.a=oa(a.getFullYear(),a.getMonth(),a.getDate()),C(this,a.getDate())):(this.a=new Date(u()),a=this.a.getDate(),this.a.setHours(0),this.a.setMinutes(0),this.a.setSeconds(0),this.a.setMilliseconds(0),C(this,a))},oa=function(a,b,c){b=new Date(a,b,c);0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b};h=D.prototype;h.getFullYear=function(){return this.a.getFullYear()};h.getMonth=function(){return this.a.getMonth()};
h.getDate=function(){return this.a.getDate()};h.getTime=function(){return this.a.getTime()};h.j=function(){return this.a.getUTCHours()};h.l=function(){return this.a.getUTCMinutes()};h.set=function(a){this.a=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
h.add=function(a){if(a.h||a.f){var b=this.getMonth()+a.f+12*a.h,c=this.getFullYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.a.setDate(1);this.a.setFullYear(c);this.a.setMonth(b);this.a.setDate(d)}a.a&&(a=new Date((new Date(this.getFullYear(),this.getMonth(),this.getDate(),12)).getTime()+864E5*a.a),this.a.setDate(1),this.a.setFullYear(a.getFullYear()),this.a.setMonth(a.getMonth()),
this.a.setDate(a.getDate()),C(this,a.getDate()))};h.i=function(a){return[this.getFullYear(),y(this.getMonth()+1),y(this.getDate())].join(a?"-":"")};h.m=function(a){return[this.a.getUTCFullYear(),y(this.a.getUTCMonth()+1),y(this.a.getUTCDate())].join(a?"-":"")};h.toString=function(){return this.i()};var C=function(a,b){a.getDate()!=b&&a.a.setUTCHours(a.a.getUTCHours()+(a.getDate()<b?1:-1))};D.prototype.valueOf=function(){return this.a.valueOf()};
var E=function(a,b,c,d,e,g,f){this.a="number"==typeof a?new Date(a,b||0,c||1,d||0,e||0,g||0,f||0):new Date(a&&a.getTime?a.getTime():u())};v(E,D);h=E.prototype;h.j=function(){return this.a.getUTCHours()};h.l=function(){return this.a.getUTCMinutes()};h.add=function(a){D.prototype.add.call(this,a);a.b&&this.a.setUTCHours(this.a.getUTCHours()+a.b);a.c&&this.a.setUTCMinutes(this.a.getUTCMinutes()+a.c);a.g&&this.a.setUTCSeconds(this.a.getUTCSeconds()+a.g)};
h.i=function(a){var b=D.prototype.i.call(this,a);return a?b+" "+y(this.a.getHours())+":"+y(this.a.getMinutes())+":"+y(this.a.getSeconds()):b+"T"+y(this.a.getHours())+y(this.a.getMinutes())+y(this.a.getSeconds())};h.m=function(a){var b=D.prototype.m.call(this,a);return a?b+" "+y(this.j())+":"+y(this.l())+":"+y(this.a.getUTCSeconds()):b+"T"+y(this.j())+y(this.l())+y(this.a.getUTCSeconds())};h.toString=function(){return this.i()};
var pa=function(a){var b=new E(2E3);a=x(a);a=a.split(-1==a.indexOf("T")?" ":"T");var c=a[0].match(la);if(c){var d=Number(c[2]),e=Number(c[3]),g=Number(c[4]);var f=Number(c[5]);var m=Number(c[6])||1;b.a.setFullYear(Number(c[1]));g?(b.a.setDate(1),b.a.setMonth(0),b.add(new B(g-1))):f?(b.a.setMonth(0),b.a.setDate(1),c=b.a.getDay()||7,b.add(new B((4>=c?1-c:8-c)+(Number(m)+7*(Number(f)-1))-1))):(d&&(b.a.setDate(1),b.a.setMonth(d-1)),e&&b.a.setDate(e));f=!0}else f=!1;f&&!(f=2>a.length)&&(a=a[1],f=a.match(na),
m=0,f&&("Z"!=f[0]&&(m=60*Number(f[2])+Number(f[3]),m*="-"==f[1]?1:-1),m-=b.a.getTimezoneOffset(),a=a.substr(0,a.length-f[0].length)),(f=a.match(ma))?(b.a.setHours(Number(f[1])),b.a.setMinutes(Number(f[2])||0),b.a.setSeconds(Number(f[3])||0),b.a.setMilliseconds(f[4]?1E3*Number(f[4]):0),0!=m&&b.a.setTime(b.getTime()+6E4*m),f=!0):f=!1);return f?b:null};
var F;a:{var qa=k.navigator;if(qa){var ra=qa.userAgent;if(ra){F=ra;break a}}F=""}var G=function(a){return-1!=F.indexOf(a)};var sa=G("Opera"),H=G("Trident")||G("MSIE"),ta=G("Edge"),ua=G("Gecko")&&!(-1!=F.toLowerCase().indexOf("webkit")&&!G("Edge"))&&!(G("Trident")||G("MSIE"))&&!G("Edge"),va=-1!=F.toLowerCase().indexOf("webkit")&&!G("Edge"),I;
a:{var J="",K=function(){var a=F;if(ua)return/rv:([^\);]+)(\)|;)/.exec(a);if(ta)return/Edge\/([\d\.]+)/.exec(a);if(H)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(va)return/WebKit\/(\S+)/.exec(a);if(sa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();K&&(J=K?K[1]:"");if(H){var L,wa=k.document;L=wa?wa.documentMode:void 0;if(null!=L&&L>(0,window.parseFloat)(J)){I=String(L);break a}}I=J}var xa=I,M={};
var O;
if(O=H){var ya;if(Object.prototype.hasOwnProperty.call(M,"9"))ya=M["9"];else{for(var P=0,za=x(String(xa)).split("."),Aa=x("9").split("."),Ba=Math.max(za.length,Aa.length),Q=0;0==P&&Q<Ba;Q++){var Ca=za[Q]||"",Da=Aa[Q]||"";do{var R=/(\d*)(\D*)(.*)/.exec(Ca)||["","","",""],S=/(\d*)(\D*)(.*)/.exec(Da)||["","","",""];if(0==R[0].length&&0==S[0].length)break;P=z(0==R[1].length?0:(0,window.parseInt)(R[1],10),0==S[1].length?0:(0,window.parseInt)(S[1],10))||z(0==R[2].length,0==S[2].length)||z(R[2],S[2]);Ca= R[3];Da=S[3]}while(0==P)}ya=M["9"]=0<=P}O=!ya}var Ea=O;
var T=function(){this.a="";this.b=Fa};T.prototype.toString=function(){return"Const{"+this.a+"}"};var Ga=function(a){return a instanceof T&&a.constructor===T&&a.b===Fa?a.a:"type_error:Const"},Fa={},Ha=function(a){var b=new T;b.a=a;return b};Ha("");var Ja=function(){this.a="";this.b=Ia},Ia={},Ka=function(a){var b=new Ja;b.a=a;return b};var La=function(a,b){b instanceof Ja&&b.constructor===Ja&&b.b===Ia?b=b.a:(ba(b),b="type_error:TrustedResourceUrl");a.src=b;if(null===n){a:{b=k.document;if((b=b.querySelector&&b.querySelector("script[nonce]"))&&(b=b.nonce||b.getAttribute("nonce"))&&aa.test(b))break a;b=null}n=b||""}(b=n)&&a.setAttribute("nonce",b)};
var Ma=function(a){var b=window.document;return l(a)?b.getElementById(a):a},Na={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Oa={IMG:" ",BR:"\n"},Pa=function(a,b,c){if(!(a.nodeName in Na))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Oa)b.push(Oa[a.nodeName]);else for(a=a.firstChild;a;)Pa(a,b,c),a=a.nextSibling};
var Qa=function(){this.a={}},Ra=function(a){"string"===typeof a.a.id&&(a.a.id=(0,window.parseInt)(a.a.id,10)||0);return a.a.id||0},Sa=function(a){a=U(a,"badge_position");return"USER_DEFINED"==a||"BOTTOM_LEFT"==a||"BOTTOM_RIGHT"==a?a:"BOTTOM_RIGHT"},Ta=function(a){return U(a,"badge_container")||U(a,"gtsContainer")},Ua=function(){var a=V("gts-o-country");return a?/^[A-z]{2}$/.test(a)?a.toUpperCase():a:""},Va=function(){var a=pa(V("gts-o-est-delivery-date")),b=pa(V("gts-o-est-ship-date"));a||(b?(a=b,
a.a.setDate(a.getDate()+7)):(a=u(),b=new E,b.a.setTime(a),a=b,a.a.setDate(a.getDate()+10)));return a.m(!0).split(" ")[0]},V=function(a){if(a=Ma(a)){if(Ea&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Pa(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Ea||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));a=x(a)}else a="";return a},U=function(a,b){var c="";"string"===typeof b&&"undefined"!==typeof a.a[b]&&(c= a.a[b]);l(c)&&c&&(c=x(c));return c},Wa=function(a){return"undefined"!==typeof window.gts&&window.gts instanceof Array?(ha(window.gts,function(a){a&&2==a.length&&"string"===typeof a[0]&&(this.a[a[0]]=a[1])},a),!!a.a&&!!Ra(a)):!1};
var Ya=function(a,b,c){var d=Xa[c];if(!d){var e=ja(c);d=e;void 0===a.style[e]&&(e=(va?"Webkit":ua?"Moz":H?"ms":sa?"O":null)+ka(e),void 0!==a.style[e]&&(d=e));Xa[c]=d}(c=d)&&(a.style[c]=b)},Xa={};var Za=function(a,b){this.b=a;this.a=b},ab=function(a){if(a.a.mcId){var b=window.document.createElement("SCRIPT"),c=Ka(Ga(Ha("https://apis.google.com/js/platform.js")));La(b,c);b.async=!0;c=[];V("gts-o-id")&&V("gts-o-email")&&Ua()&&Va()&&c.push(t(a.f,a));a.a.showBadge&&("USER_DEFINED"==Sa(a.b)&&Ta(a.b)?$a(a):c.push(t(a.c,a)));b.onload=ha(c,function(a){a()});U(a.b,"locale")&&p("gapi.config").update("lang",U(a.b,"locale"));window.document.body.appendChild(b)}},$a=function(a){var b=window.document.createElement("g:ratingbadge");
b.setAttribute("merchant_id",a.a.mcId);if(l("position"))Ya(b,"relative","position");else for(var c in"position")Ya(b,"position"[c],c);(a=Ma(Ta(a.b)))&&a.appendChild(b)};Za.prototype.c=function(){var a=window.document.createElement("div");window.document.body.appendChild(a);p("gapi.load")("ratingbadge",t(function(){p("gapi.ratingbadge.render")(a,{merchant_id:this.a.mcId,position:Sa(this.b)})},this))};
Za.prototype.f=function(){p("gapi.load")("surveyoptin",t(function(){p("gapi.surveyoptin.render")({merchant_id:this.a.mcId,order_id:V("gts-o-id"),email:V("gts-o-email"),delivery_country:Ua(),estimated_delivery_date:Va(),opt_in_style:this.a.optInStyle})},this))};
var bb=function(a,b){this.c=a;this.f=b;this.b=0;this.a=null};bb.prototype.get=function(){if(0<this.b){this.b--;var a=this.a;this.a=a.next;a.next=null}else a=this.c();return a};var cb=function(a,b){a.f(b);100>a.b&&(a.b++,b.next=a.a,a.a=b)};var db=function(a){k.setTimeout(function(){throw a;},0)},eb,fb=function(){var a=k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!G("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+
"//"+b.location.host;a=t(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!G("Trident")&&!G("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var a=c.o;c.o=null;a()}};return function(a){d.next={o:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")? function(a){var b=window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){k.setTimeout(a,0)}};
var gb=function(){this.b=this.a=null},ib=new bb(function(){return new hb},function(a){a.reset()});gb.prototype.add=function(a,b){var c=ib.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};var kb=function(){var a=jb,b=null;a.a&&(b=a.a,a.a=a.a.next,a.a||(a.b=null),b.next=null);return b},hb=function(){this.next=this.b=this.a=null};hb.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};hb.prototype.reset=function(){this.next=this.b=this.a=null};
var nb=function(a,b){W||lb();mb||(W(),mb=!0);jb.add(a,b)},W,lb=function(){if(k.Promise&&k.Promise.resolve){var a=k.Promise.resolve(void 0);W=function(){a.then(ob)}}else W=function(){var a=ob;!r(k.setImmediate)||k.Window&&k.Window.prototype&&!G("Edge")&&k.Window.prototype.setImmediate==k.setImmediate?(eb||(eb=fb()),eb(a)):k.setImmediate(a)}},mb=!1,jb=new gb,ob=function(){for(var a;a=kb();){try{a.a.call(a.b)}catch(b){db(b)}cb(ib,a)}mb=!1};
var Y=function(a){this.a=0;this.s=void 0;this.f=this.b=this.c=null;this.g=this.h=!1;if(a!=q)try{var b=this;a.call(void 0,function(a){X(b,2,a)},function(a){X(b,3,a)})}catch(c){X(this,3,c)}},pb=function(){this.next=this.c=this.b=this.f=this.a=null;this.g=!1};pb.prototype.reset=function(){this.c=this.b=this.f=this.a=null;this.g=!1};
var qb=new bb(function(){return new pb},function(a){a.reset()}),rb=function(a,b,c){var d=qb.get();d.f=a;d.b=b;d.c=c;return d},sb=function(a){if(a instanceof Y)return a;var b=new Y(q);X(b,2,a);return b};Y.prototype.then=function(a,b,c){return tb(this,r(a)?a:null,r(b)?b:null,c)};Y.prototype.then=Y.prototype.then;Y.prototype.$goog_Thenable=!0;Y.prototype.cancel=function(a){0==this.a&&nb(function(){var b=new Z(a);ub(this,b)},this)};
var ub=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,g=null,f=c.b;f&&(f.g||(d++,f.a==a&&(e=f),!(e&&1<d)));f=f.next)e||(g=f);e&&(0==c.a&&1==d?ub(c,b):(g?(d=g,d.next==c.f&&(c.f=d),d.next=d.next.next):vb(c),wb(c,e,3,b)))}a.c=null}else X(a,3,b)},yb=function(a,b){a.b||2!=a.a&&3!=a.a||xb(a);a.f?a.f.next=b:a.b=b;a.f=b},tb=function(a,b,c,d){var e=rb(null,null,null);e.a=new Y(function(a,f){e.f=b?function(c){try{var e=b.call(d,c);a(e)}catch(A){f(A)}}:a;e.b=c?function(b){try{var e=c.call(d,
b);void 0===e&&b instanceof Z?f(b):a(e)}catch(A){f(A)}}:f});e.a.c=a;yb(a,e);return e.a};Y.prototype.v=function(a){this.a=0;X(this,2,a)};Y.prototype.w=function(a){this.a=0;X(this,3,a)};
var X=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;a:{var d=c,e=a.v,g=a.w;if(d instanceof Y){yb(d,rb(e||q,g||null,a));var f=!0}else{if(d)try{var m=!!d.$goog_Thenable}catch(A){m=!1}else m=!1;if(m)d.then(e,g,a),f=!0;else{if(ca(d))try{var N=d.then;if(r(N)){zb(d,N,e,g,a);f=!0;break a}}catch(A){g.call(a,A);f=!0;break a}f=!1}}}f||(a.s=c,a.a=b,a.c=null,xb(a),3!=b||c instanceof Z||Ab(a,c))}},zb=function(a,b,c,d,e){var g=!1,f=function(a){g||(g=!0,c.call(e,
a))},m=function(a){g||(g=!0,d.call(e,a))};try{b.call(a,f,m)}catch(N){m(N)}},xb=function(a){a.h||(a.h=!0,nb(a.u,a))},vb=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.f=null);return b};Y.prototype.u=function(){for(var a;a=vb(this);)wb(this,a,this.a,this.s);this.h=!1};
var wb=function(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.g;a=a.c)a.g=!1;if(b.a)b.a.c=null,Bb(b,c,d);else try{b.g?b.f.call(b.c):Bb(b,c,d)}catch(e){Cb.call(null,e)}cb(qb,b)},Bb=function(a,b,c){2==b?a.f.call(a.c,c):a.b&&a.b.call(a.c,c)},Ab=function(a,b){a.g=!0;nb(function(){a.g&&Cb.call(null,b)})},Cb=db,Z=function(a){w.call(this,a)};v(Z,w);Z.prototype.name="cancel";
var Db,Eb=Ka(Ga(Ha("https://apis.google.com/js/api.js"))),Gb=function(){return Fb().then(function(a){return new Y(function(b,c){a.load("gapi.iframes",{callback:fa(b,a),timeout:1E4,ontimeout:function(){c(Error("b`gapi.iframes"))}})})})},Fb=function(){var a=window;return a.gapi?sb(a.gapi):Db?Db:Db=new Y(function(b,c){var d=window.document.createElement("SCRIPT");La(d,Eb);d.onload=function(){b(a.gapi)};d.onerror=function(){c("Failed to load gapi.")};window.document.getElementsByTagName("head")[0].appendChild(d)})};
(function(){var a=window._DumpException||function(a){throw a;};window._DumpException=a;var b=new Qa;Wa(b)&&Gb().then(function(){var a=p("gapi.iframes.getContext")(),d=window.document.createElement("div");d.setAttribute("style","position: absolute; width: 1px; height: 1px; left: -10000px; display: none; aria-hidden: true");window.document.body.appendChild(d);var e=window._gcr_server_address+"/shopping/customerreviews/proxy",g=window.location.href;/(yahoo|shopify.com|luminatestores|shopserve.jp)/.test(g)|| (g=window.location.origin);d={url:e,queryParams:{ts_id:Ra(b),origin:g},allowPost:!1,where:d};a.openChild(d).register("merchantProperty",function(a){ab(new Za(b,a))},p("gapi.iframes.CROSS_ORIGIN_IFRAMES_FILTER",window))},function(){})})();

}catch(e){_._DumpException(e)}
}).call(this,this.shopping_verified_reviews_VerifiedReviewsGcrBootstrapJs);
// Google Inc.
