function randomAdv(ab_hash){var adv=new Array();var keys=new Array();for(var i in ab_hash){if(i!=""&&ab_hash[i]!=""){adv.push(ab_hash[i]);keys.push(i);}}
var m=0,x=0,y=0;var ad=new Array();var hit=new Array();hit[0]=1;hit[1]=1;hit[2]=1;for(i=0;i<=adv.length-1;i++){m+=hit[i];}
n=Math.floor(Math.random()*m);n++;for(i=0;i<=adv.length-1;i++){x=y;y+=hit[i];var obj={};obj[keys[i]]=adv[i];if(x<n&&n<=y)ad=obj;}
return ad;}
function onVisible(){var add_style=document.createElement('style');add_style.type="text/css";document.getElementsByTagName('head').item(0).appendChild(add_style);css=document.styleSheets.item(0)
var idx=document.styleSheets[0].cssRules.length;css.insertRule(".rewrite_ab{ visibility:hidden; }",idx);}
onVisible();function rewrite_topics_titles(rand_topics_title_hash){for(var key in rand_topics_title_hash){var rand_title=rand_topics_title_hash[key];for(var title_index in rand_title){if(title_index!=""&&rand_title[title_index]!=""){$("a[id='"+key+"']").html(rand_title[title_index]);var url=$("a[id='"+key+"']").attr("href");if(url){url=url+"?rt="+title_index;$("a[id='"+key+"']").attr("href",url);}}}}}
function rewrite_headline_titles(rand_headline_title_hash,rand_headline_category_hash){for(var key in rand_headline_title_hash){var rand_title=rand_headline_title_hash[key];var topics_category_id=rand_headline_category_hash[key];for(var title_index in rand_title){if(title_index!=""&&rand_title[title_index]!=""){$("a[id='"+key+"']").html(rand_title[title_index]);var url=$("a[id='"+key+"']").attr("href");if(url&&topics_category_id){url=url+"?rt="+title_index+"&tcid="+topics_category_id;$("a[id='"+key+"']").attr("href",url);}}}}}
function rewrite_topics_link(rand_topics_title_hash){for(var key in rand_topics_title_hash){var rand_title=rand_topics_title_hash[key];for(var title_index in rand_title){if(title_index!=""&&rand_title[title_index]!=""){var url=$("a[id='"+key+"']").attr("href");if(url){url=url+"?rt="+title_index;$("a[id='"+key+"']").attr("href",url);}}}}}
function rewrite_headline_link(rand_headline_title_hash,rand_headline_category_hash){for(var key in rand_headline_title_hash){var rand_title=rand_headline_title_hash[key];var topics_category_id=rand_headline_category_hash[key];for(var title_index in rand_title){if(title_index!=""&&rand_title[title_index]!=""){var url=$("a[id='"+key+"']").attr("href");if(url){url=url+"?rt="+title_index+"&tcid="+topics_category_id;$("a[id='"+key+"']").attr("href",url);}}}}}
function rewrite_titles_image(rand_title_hash){for(key in rand_title_hash){var rand_title=rand_title_hash[key];for(var title_index in rand_title){if(title_index!=""&&rand_title[title_index]!=""){$("img[id='"+key+"']").attr("alt",rand_title[title_index]);$("img[id='"+key+"']").attr("title",rand_title[title_index]);}}}}
function rewrite_titles_image_alt(rand_title_hash){for(key in rand_title_hash){var rand_title=rand_title_hash[key];for(var title_index in rand_title){if(title_index!=""&&rand_title[title_index]!=""){$("img[id='"+key+"']").attr("alt",rand_title[title_index]);}}}}
